// Written by tools/build_decks.py from content/decks/*.tsv and content/buddy.tsv.
// Do not edit by hand: change the tables and run the tool again.
//
// Readings and meanings are checked against JMdict (Electronic Dictionary Research and
// Development Group, CC BY-SA 4.0). Pitch accents come from the accent list of the Kanjium
// project (CC BY-SA 4.0). The decks themselves are therefore shared under CC BY-SA 4.0.
#include "deck.h"

namespace {

const deck::Item kItems_hiragana[] = {
    {"hiragana-a", "あ", "あ", "", "a", "a as in father", "", -1, 1, deck::Kind::Kana},
    {"hiragana-i", "い", "い", "", "i", "i as in machine", "", -1, 1, deck::Kind::Kana},
    {"hiragana-u", "う", "う", "", "u", "u as in flute, lips relaxed", "", -1, 1, deck::Kind::Kana},
    {"hiragana-e", "え", "え", "", "e", "e as in bed", "", -1, 1, deck::Kind::Kana},
    {"hiragana-o", "お", "お", "", "o", "o as in more", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ka", "か", "か", "", "ka", "ka as in car", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ki", "き", "き", "", "ki", "ki as in key", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ku", "く", "く", "", "ku", "ku as in cool", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ke", "け", "け", "", "ke", "ke as in kettle", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ko", "こ", "こ", "", "ko", "ko as in coat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-sa", "さ", "さ", "", "sa", "sa as in salsa", "", -1, 1, deck::Kind::Kana},
    {"hiragana-shi", "し", "し", "", "shi", "shi as in sheep; there is no si", "", -1, 1, deck::Kind::Kana},
    {"hiragana-su", "す", "す", "", "su", "su as in soup", "", -1, 1, deck::Kind::Kana},
    {"hiragana-se", "せ", "せ", "", "se", "se as in set", "", -1, 1, deck::Kind::Kana},
    {"hiragana-so", "そ", "そ", "", "so", "so as in sort", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ta", "た", "た", "", "ta", "ta as in tar", "", -1, 1, deck::Kind::Kana},
    {"hiragana-chi", "ち", "ち", "", "chi", "chi as in cheese; there is no ti", "", -1, 1, deck::Kind::Kana},
    {"hiragana-tsu", "つ", "つ", "", "tsu", "tsu as in cats; there is no tu", "", -1, 1, deck::Kind::Kana},
    {"hiragana-te", "て", "て", "", "te", "te as in ten", "", -1, 1, deck::Kind::Kana},
    {"hiragana-to", "と", "と", "", "to", "to as in tall", "", -1, 1, deck::Kind::Kana},
    {"hiragana-na", "な", "な", "", "na", "na as in nacho", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ni", "に", "に", "", "ni", "ni as in knee", "", -1, 1, deck::Kind::Kana},
    {"hiragana-nu", "ぬ", "ぬ", "", "nu", "nu as in noon", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ne", "ね", "ね", "", "ne", "ne as in net", "", -1, 1, deck::Kind::Kana},
    {"hiragana-no", "の", "の", "", "no", "no as in north", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ha", "は", "は", "", "ha", "ha as in harp; as topic marker said wa", "", -1, 1, deck::Kind::Kana},
    {"hiragana-hi", "ひ", "ひ", "", "hi", "hi as in he", "", -1, 1, deck::Kind::Kana},
    {"hiragana-fu", "ふ", "ふ", "", "fu", "fu: a soft f, lips only", "", -1, 1, deck::Kind::Kana},
    {"hiragana-he", "へ", "へ", "", "he", "he as in hen; as direction marker said e", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ho", "ほ", "ほ", "", "ho", "ho as in horn", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ma", "ま", "ま", "", "ma", "ma as in mama", "", -1, 1, deck::Kind::Kana},
    {"hiragana-mi", "み", "み", "", "mi", "mi as in me", "", -1, 1, deck::Kind::Kana},
    {"hiragana-mu", "む", "む", "", "mu", "mu as in moon", "", -1, 1, deck::Kind::Kana},
    {"hiragana-me", "め", "め", "", "me", "me as in met", "", -1, 1, deck::Kind::Kana},
    {"hiragana-mo", "も", "も", "", "mo", "mo as in more", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ya", "や", "や", "", "ya", "ya as in yard", "", -1, 1, deck::Kind::Kana},
    {"hiragana-yu", "ゆ", "ゆ", "", "yu", "yu as in you", "", -1, 1, deck::Kind::Kana},
    {"hiragana-yo", "よ", "よ", "", "yo", "yo as in your", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ra", "ら", "ら", "", "ra", "ra: a light tap, between r, l and d", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ri", "り", "り", "", "ri", "ri: a light tap, as in the tt of city", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ru", "る", "る", "", "ru", "ru: a light tap", "", -1, 1, deck::Kind::Kana},
    {"hiragana-re", "れ", "れ", "", "re", "re: a light tap", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ro", "ろ", "ろ", "", "ro", "ro: a light tap", "", -1, 1, deck::Kind::Kana},
    {"hiragana-wa", "わ", "わ", "", "wa", "wa as in watt", "", -1, 1, deck::Kind::Kana},
    {"hiragana-wo", "を", "を", "", "wo", "o; typed wo; marks the object", "", -1, 1, deck::Kind::Kana},
    {"hiragana-nn", "ん", "ん", "", "nn", "n: a hum; typed nn, or n before a consonant", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ga", "が", "が", "", "ga", "ga: か with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-gi", "ぎ", "ぎ", "", "gi", "gi: き with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-gu", "ぐ", "ぐ", "", "gu", "gu: く with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ge", "げ", "げ", "", "ge", "ge: け with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-go", "ご", "ご", "", "go", "go: こ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-za", "ざ", "ざ", "", "za", "za: さ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ji", "じ", "じ", "", "ji", "ji as in jeep: し with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-zu", "ず", "ず", "", "zu", "zu: す with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ze", "ぜ", "ぜ", "", "ze", "ze: せ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-zo", "ぞ", "ぞ", "", "zo", "zo: そ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-da", "だ", "だ", "", "da", "da: た with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-di", "ぢ", "ぢ", "", "di", "ji, rare; typed di: ち with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-du", "づ", "づ", "", "du", "zu, rare; typed du: つ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-de", "で", "で", "", "de", "de: て with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-do", "ど", "ど", "", "do", "do: と with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ba", "ば", "ば", "", "ba", "ba: は with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-bi", "び", "び", "", "bi", "bi: ひ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-bu", "ぶ", "ぶ", "", "bu", "bu: ふ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-be", "べ", "べ", "", "be", "be: へ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-bo", "ぼ", "ぼ", "", "bo", "bo: ほ with two dots", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pa", "ぱ", "ぱ", "", "pa", "pa: は with a small circle", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pi", "ぴ", "ぴ", "", "pi", "pi: ひ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pu", "ぷ", "ぷ", "", "pu", "pu: ふ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pe", "ぺ", "ぺ", "", "pe", "pe: へ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"hiragana-po", "ぽ", "ぽ", "", "po", "po: ほ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"hiragana-kya", "きゃ", "きゃ", "", "kya", "kya: き and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-kyu", "きゅ", "きゅ", "", "kyu", "kyu: き and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-kyo", "きょ", "きょ", "", "kyo", "kyo: き and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-sha", "しゃ", "しゃ", "", "sha", "sha: し and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-shu", "しゅ", "しゅ", "", "shu", "shu: し and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-sho", "しょ", "しょ", "", "sho", "sho: し and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-cha", "ちゃ", "ちゃ", "", "cha", "cha: ち and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-chu", "ちゅ", "ちゅ", "", "chu", "chu: ち and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-cho", "ちょ", "ちょ", "", "cho", "cho: ち and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-nya", "にゃ", "にゃ", "", "nya", "nya: に and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-nyu", "にゅ", "にゅ", "", "nyu", "nyu: に and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-nyo", "にょ", "にょ", "", "nyo", "nyo: に and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-hya", "ひゃ", "ひゃ", "", "hya", "hya: ひ and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-hyu", "ひゅ", "ひゅ", "", "hyu", "hyu: ひ and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-hyo", "ひょ", "ひょ", "", "hyo", "hyo: ひ and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-mya", "みゃ", "みゃ", "", "mya", "mya: み and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-myu", "みゅ", "みゅ", "", "myu", "myu: み and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-myo", "みょ", "みょ", "", "myo", "myo: み and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-rya", "りゃ", "りゃ", "", "rya", "rya: り and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ryu", "りゅ", "りゅ", "", "ryu", "ryu: り and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ryo", "りょ", "りょ", "", "ryo", "ryo: り and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-gya", "ぎゃ", "ぎゃ", "", "gya", "gya: ぎ and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-gyu", "ぎゅ", "ぎゅ", "", "gyu", "gyu: ぎ and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-gyo", "ぎょ", "ぎょ", "", "gyo", "gyo: ぎ and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ja", "じゃ", "じゃ", "", "ja", "ja: じ and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-ju", "じゅ", "じゅ", "", "ju", "ju: じ and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-jo", "じょ", "じょ", "", "jo", "jo: じ and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-bya", "びゃ", "びゃ", "", "bya", "bya: び and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-byu", "びゅ", "びゅ", "", "byu", "byu: び and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-byo", "びょ", "びょ", "", "byo", "byo: び and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pya", "ぴゃ", "ぴゃ", "", "pya", "pya: ぴ and a small ゃ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pyu", "ぴゅ", "ぴゅ", "", "pyu", "pyu: ぴ and a small ゅ, one beat", "", -1, 1, deck::Kind::Kana},
    {"hiragana-pyo", "ぴょ", "ぴょ", "", "pyo", "pyo: ぴ and a small ょ, one beat", "", -1, 1, deck::Kind::Kana},
};

const deck::Item kItems_katakana[] = {
    {"katakana-a", "ア", "ア", "", "a", "a: マ ma with a leg down", "", -1, 1, deck::Kind::Kana},
    {"katakana-i", "イ", "イ", "", "i", "i as in machine; same as い", "", -1, 1, deck::Kind::Kana},
    {"katakana-u", "ウ", "ウ", "", "u", "u: a tick on top. ワ wa has none", "", -1, 1, deck::Kind::Kana},
    {"katakana-e", "エ", "エ", "", "e", "e as in bed; same as え", "", -1, 1, deck::Kind::Kana},
    {"katakana-o", "オ", "オ", "", "o", "o as in more; same as お", "", -1, 1, deck::Kind::Kana},
    {"katakana-ka", "カ", "カ", "", "ka", "ka as in car; same as か", "", -1, 1, deck::Kind::Kana},
    {"katakana-ki", "キ", "キ", "", "ki", "ki as in key; same as き", "", -1, 1, deck::Kind::Kana},
    {"katakana-ku", "ク", "ク", "", "ku", "ku: no bar inside. ケ ke and タ ta have one", "", -1, 1, deck::Kind::Kana},
    {"katakana-ke", "ケ", "ケ", "", "ke", "ke: the bar sticks out to the left", "", -1, 1, deck::Kind::Kana},
    {"katakana-ko", "コ", "コ", "", "ko", "ko: open to the left. ユ yu has a long base", "", -1, 1, deck::Kind::Kana},
    {"katakana-sa", "サ", "サ", "", "sa", "sa as in salsa; same as さ", "", -1, 1, deck::Kind::Kana},
    {"katakana-shi", "シ", "シ", "", "shi", "shi: strokes rise from the left. ツ tsu falls", "", -1, 1, deck::Kind::Kana},
    {"katakana-su", "ス", "ス", "", "su", "su: ends open. ヌ nu has a stroke across", "", -1, 1, deck::Kind::Kana},
    {"katakana-se", "セ", "セ", "", "se", "se as in set; same as せ", "", -1, 1, deck::Kind::Kana},
    {"katakana-so", "ソ", "ソ", "", "so", "so: the long stroke falls. ン n rises", "", -1, 1, deck::Kind::Kana},
    {"katakana-ta", "タ", "タ", "", "ta", "ta: ク ku with a short stroke inside", "", -1, 1, deck::Kind::Kana},
    {"katakana-chi", "チ", "チ", "", "chi", "chi: the top stroke slants. テ te is flat", "", -1, 1, deck::Kind::Kana},
    {"katakana-tsu", "ツ", "ツ", "", "tsu", "tsu: strokes fall from the top. シ shi rises", "", -1, 1, deck::Kind::Kana},
    {"katakana-te", "テ", "テ", "", "te", "te: two flat bars. チ chi slants on top", "", -1, 1, deck::Kind::Kana},
    {"katakana-to", "ト", "ト", "", "to", "to as in tall; same as と", "", -1, 1, deck::Kind::Kana},
    {"katakana-na", "ナ", "ナ", "", "na", "na as in nacho; same as な", "", -1, 1, deck::Kind::Kana},
    {"katakana-ni", "ニ", "ニ", "", "ni", "ni as in knee; same as に", "", -1, 1, deck::Kind::Kana},
    {"katakana-nu", "ヌ", "ヌ", "", "nu", "nu: ス su with a stroke across", "", -1, 1, deck::Kind::Kana},
    {"katakana-ne", "ネ", "ネ", "", "ne", "ne as in net; same as ね", "", -1, 1, deck::Kind::Kana},
    {"katakana-no", "ノ", "ノ", "", "no", "no: one stroke. ソ so and ン n have two", "", -1, 1, deck::Kind::Kana},
    {"katakana-ha", "ハ", "ハ", "", "ha", "ha as in harp; same as は", "", -1, 1, deck::Kind::Kana},
    {"katakana-hi", "ヒ", "ヒ", "", "hi", "hi as in he; same as ひ", "", -1, 1, deck::Kind::Kana},
    {"katakana-fu", "フ", "フ", "", "fu", "fu: one corner only. ワ wa has a left side", "", -1, 1, deck::Kind::Kana},
    {"katakana-he", "ヘ", "ヘ", "", "he", "he as in hen; same as へ", "", -1, 1, deck::Kind::Kana},
    {"katakana-ho", "ホ", "ホ", "", "ho", "ho as in horn; same as ほ", "", -1, 1, deck::Kind::Kana},
    {"katakana-ma", "マ", "マ", "", "ma", "ma: the dot is inside. ム mu stands on a base", "", -1, 1, deck::Kind::Kana},
    {"katakana-mi", "ミ", "ミ", "", "mi", "mi as in me; same as み", "", -1, 1, deck::Kind::Kana},
    {"katakana-mu", "ム", "ム", "", "mu", "mu: a base line with a dot. マ ma is a corner", "", -1, 1, deck::Kind::Kana},
    {"katakana-me", "メ", "メ", "", "me", "me as in met; same as め", "", -1, 1, deck::Kind::Kana},
    {"katakana-mo", "モ", "モ", "", "mo", "mo as in more; same as も", "", -1, 1, deck::Kind::Kana},
    {"katakana-ya", "ヤ", "ヤ", "", "ya", "ya as in yard; same as や", "", -1, 1, deck::Kind::Kana},
    {"katakana-yu", "ユ", "ユ", "", "yu", "yu: the base is longer than the top", "", -1, 1, deck::Kind::Kana},
    {"katakana-yo", "ヨ", "ヨ", "", "yo", "yo: three bars. コ ko has two", "", -1, 1, deck::Kind::Kana},
    {"katakana-ra", "ラ", "ラ", "", "ra", "ra: a light tap, between r, l and d; same as ら", "", -1, 1, deck::Kind::Kana},
    {"katakana-ri", "リ", "リ", "", "ri", "ri: a light tap, as in the tt of city; same as り", "", -1, 1, deck::Kind::Kana},
    {"katakana-ru", "ル", "ル", "", "ru", "ru: a light tap; same as る", "", -1, 1, deck::Kind::Kana},
    {"katakana-re", "レ", "レ", "", "re", "re: a light tap; same as れ", "", -1, 1, deck::Kind::Kana},
    {"katakana-ro", "ロ", "ロ", "", "ro", "ro: a light tap; same as ろ", "", -1, 1, deck::Kind::Kana},
    {"katakana-wa", "ワ", "ワ", "", "wa", "wa: flat on top. ウ u has a tick", "", -1, 1, deck::Kind::Kana},
    {"katakana-wo", "ヲ", "ヲ", "", "wo", "o, rare; typed wo; same as を", "", -1, 1, deck::Kind::Kana},
    {"katakana-nn", "ン", "ン", "", "nn", "n: the long stroke rises. ソ so falls", "", -1, 1, deck::Kind::Kana},
    {"katakana-ga", "ガ", "ガ", "", "ga", "ga: カ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-gi", "ギ", "ギ", "", "gi", "gi: キ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-gu", "グ", "グ", "", "gu", "gu: ク with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-ge", "ゲ", "ゲ", "", "ge", "ge: ケ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-go", "ゴ", "ゴ", "", "go", "go: コ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-za", "ザ", "ザ", "", "za", "za: サ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-ji", "ジ", "ジ", "", "ji", "ji as in jeep: シ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-zu", "ズ", "ズ", "", "zu", "zu: ス with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-ze", "ゼ", "ゼ", "", "ze", "ze: セ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-zo", "ゾ", "ゾ", "", "zo", "zo: ソ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-da", "ダ", "ダ", "", "da", "da: タ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-di", "ヂ", "ヂ", "", "di", "ji, rare; typed di: チ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-du", "ヅ", "ヅ", "", "du", "zu, rare; typed du: ツ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-de", "デ", "デ", "", "de", "de: テ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-do", "ド", "ド", "", "do", "do: ト with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-ba", "バ", "バ", "", "ba", "ba: ハ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-bi", "ビ", "ビ", "", "bi", "bi: ヒ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-bu", "ブ", "ブ", "", "bu", "bu: フ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-be", "ベ", "ベ", "", "be", "be: ヘ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-bo", "ボ", "ボ", "", "bo", "bo: ホ with two dots", "", -1, 1, deck::Kind::Kana},
    {"katakana-pa", "パ", "パ", "", "pa", "pa: ハ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"katakana-pi", "ピ", "ピ", "", "pi", "pi: ヒ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"katakana-pu", "プ", "プ", "", "pu", "pu: フ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"katakana-pe", "ペ", "ペ", "", "pe", "pe: ヘ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"katakana-po", "ポ", "ポ", "", "po", "po: ホ with a small circle", "", -1, 1, deck::Kind::Kana},
    {"katakana-kya", "キャ", "キャ", "", "kya", "kya: キ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-kyu", "キュ", "キュ", "", "kyu", "kyu: キ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-kyo", "キョ", "キョ", "", "kyo", "kyo: キ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-sha", "シャ", "シャ", "", "sha", "sha: シ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-shu", "シュ", "シュ", "", "shu", "shu: シ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-sho", "ショ", "ショ", "", "sho", "sho: シ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-cha", "チャ", "チャ", "", "cha", "cha: チ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-chu", "チュ", "チュ", "", "chu", "chu: チ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-cho", "チョ", "チョ", "", "cho", "cho: チ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-nya", "ニャ", "ニャ", "", "nya", "nya: ニ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-nyu", "ニュ", "ニュ", "", "nyu", "nyu: ニ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-nyo", "ニョ", "ニョ", "", "nyo", "nyo: ニ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-hya", "ヒャ", "ヒャ", "", "hya", "hya: ヒ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-hyu", "ヒュ", "ヒュ", "", "hyu", "hyu: ヒ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-hyo", "ヒョ", "ヒョ", "", "hyo", "hyo: ヒ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-mya", "ミャ", "ミャ", "", "mya", "mya: ミ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-myu", "ミュ", "ミュ", "", "myu", "myu: ミ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-myo", "ミョ", "ミョ", "", "myo", "myo: ミ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-rya", "リャ", "リャ", "", "rya", "rya: リ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-ryu", "リュ", "リュ", "", "ryu", "ryu: リ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-ryo", "リョ", "リョ", "", "ryo", "ryo: リ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-gya", "ギャ", "ギャ", "", "gya", "gya: ギ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-gyu", "ギュ", "ギュ", "", "gyu", "gyu: ギ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-gyo", "ギョ", "ギョ", "", "gyo", "gyo: ギ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-ja", "ジャ", "ジャ", "", "ja", "ja: ジ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-ju", "ジュ", "ジュ", "", "ju", "ju: ジ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-jo", "ジョ", "ジョ", "", "jo", "jo: ジ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-bya", "ビャ", "ビャ", "", "bya", "bya: ビ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-byu", "ビュ", "ビュ", "", "byu", "byu: ビ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-byo", "ビョ", "ビョ", "", "byo", "byo: ビ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-pya", "ピャ", "ピャ", "", "pya", "pya: ピ and a small ャ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-pyu", "ピュ", "ピュ", "", "pyu", "pyu: ピ and a small ュ, one beat", "", -1, 1, deck::Kind::Kana},
    {"katakana-pyo", "ピョ", "ピョ", "", "pyo", "pyo: ピ and a small ョ, one beat", "", -1, 1, deck::Kind::Kana},
};

const deck::Item kItems_numbers[] = {
    {"num-yen-1", "¥1", "いちえん", "", "1 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-4", "¥4", "よえん", "", "4 yen", "4 is よ before えん", "", -1, 1, deck::Kind::Number},
    {"num-yen-5", "¥5", "ごえん", "", "5 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-7", "¥7", "ななえん", "しちえん", "7 yen", "しちえん is also said", "", -1, 1, deck::Kind::Number},
    {"num-yen-9", "¥9", "きゅうえん", "", "9 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-10", "¥10", "じゅうえん", "", "10 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-14", "¥14", "じゅうよえん", "", "14 yen", "4 is よ before えん: じゅうよえん", "", -1, 1, deck::Kind::Number},
    {"num-yen-50", "¥50", "ごじゅうえん", "", "50 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-100", "¥100", "ひゃくえん", "", "100 yen", "ひゃく alone, no いち in front", "", -1, 1, deck::Kind::Number},
    {"num-yen-110", "¥110", "ひゃくじゅうえん", "", "110 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-150", "¥150", "ひゃくごじゅうえん", "", "150 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-160", "¥160", "ひゃくろくじゅうえん", "", "160 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-198", "¥198", "ひゃくきゅうじゅうはちえん", "", "198 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-230", "¥230", "にひゃくさんじゅうえん", "", "230 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-300", "¥300", "さんびゃくえん", "", "300 yen", "さんびゃく, not さんひゃく", "", -1, 1, deck::Kind::Number},
    {"num-yen-324", "¥324", "さんびゃくにじゅうよえん", "", "324 yen", "4 is よ before えん", "", -1, 1, deck::Kind::Number},
    {"num-yen-390", "¥390", "さんびゃくきゅうじゅうえん", "", "390 yen", "さんびゃく, not さんひゃく", "", -1, 1, deck::Kind::Number},
    {"num-yen-440", "¥440", "よんひゃくよんじゅうえん", "", "440 yen", "よん in front of ひゃく and じゅう", "", -1, 1, deck::Kind::Number},
    {"num-yen-500", "¥500", "ごひゃくえん", "", "500 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-600", "¥600", "ろっぴゃくえん", "", "600 yen", "ろっぴゃく, not ろくひゃく", "", -1, 1, deck::Kind::Number},
    {"num-yen-680", "¥680", "ろっぴゃくはちじゅうえん", "", "680 yen", "ろっぴゃく, not ろくひゃく", "", -1, 1, deck::Kind::Number},
    {"num-yen-770", "¥770", "ななひゃくななじゅうえん", "ななひゃくしちじゅうえん|しちひゃくななじゅうえん|しちひゃくしちじゅうえん", "770 yen", "also しちひゃく and しちじゅう", "", -1, 1, deck::Kind::Number},
    {"num-yen-800", "¥800", "はっぴゃくえん", "", "800 yen", "はっぴゃく, not はちひゃく", "", -1, 1, deck::Kind::Number},
    {"num-yen-880", "¥880", "はっぴゃくはちじゅうえん", "", "880 yen", "はっぴゃく, but はちじゅう", "", -1, 1, deck::Kind::Number},
    {"num-yen-980", "¥980", "きゅうひゃくはちじゅうえん", "", "980 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-1000", "¥1,000", "せんえん", "", "1,000 yen", "せん alone, no いち in front", "", -1, 1, deck::Kind::Number},
    {"num-yen-1005", "¥1,005", "せんごえん", "", "1,005 yen", "zeros are skipped: せん ご えん", "", -1, 1, deck::Kind::Number},
    {"num-yen-1050", "¥1,050", "せんごじゅうえん", "", "1,050 yen", "zeros are skipped", "", -1, 1, deck::Kind::Number},
    {"num-yen-1280", "¥1,280", "せんにひゃくはちじゅうえん", "", "1,280 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-1600", "¥1,600", "せんろっぴゃくえん", "", "1,600 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-1980", "¥1,980", "せんきゅうひゃくはちじゅうえん", "", "1,980 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-2008", "¥2,008", "にせんはちえん", "", "2,008 yen", "zeros are skipped: にせん はち えん", "", -1, 1, deck::Kind::Number},
    {"num-yen-2400", "¥2,400", "にせんよんひゃくえん", "", "2,400 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-3000", "¥3,000", "さんぜんえん", "", "3,000 yen", "さんぜん, not さんせん", "", -1, 1, deck::Kind::Number},
    {"num-yen-3300", "¥3,300", "さんぜんさんびゃくえん", "", "3,300 yen", "さんぜん さんびゃく: both change", "", -1, 1, deck::Kind::Number},
    {"num-yen-3600", "¥3,600", "さんぜんろっぴゃくえん", "", "3,600 yen", "さんぜん ろっぴゃく: both change", "", -1, 1, deck::Kind::Number},
    {"num-yen-4800", "¥4,800", "よんせんはっぴゃくえん", "", "4,800 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-5000", "¥5,000", "ごせんえん", "", "5,000 yen", "typed gosen'en: n' before えん", "", -1, 1, deck::Kind::Number},
    {"num-yen-6300", "¥6,300", "ろくせんさんびゃくえん", "", "6,300 yen", "ろくせん, but さんびゃく", "", -1, 1, deck::Kind::Number},
    {"num-yen-7000", "¥7,000", "ななせんえん", "しちせんえん", "7,000 yen", "しちせん is also said", "", -1, 1, deck::Kind::Number},
    {"num-yen-8000", "¥8,000", "はっせんえん", "", "8,000 yen", "はっせん, not はちせん", "", -1, 1, deck::Kind::Number},
    {"num-yen-8800", "¥8,800", "はっせんはっぴゃくえん", "", "8,800 yen", "はっせん はっぴゃく: both change", "", -1, 1, deck::Kind::Number},
    {"num-yen-9900", "¥9,900", "きゅうせんきゅうひゃくえん", "", "9,900 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-10000", "¥10,000", "いちまんえん", "", "10,000 yen", "まん needs いち in front", "", -1, 1, deck::Kind::Number},
    {"num-yen-10500", "¥10,500", "いちまんごひゃくえん", "", "10,500 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-12000", "¥12,000", "いちまんにせんえん", "", "12,000 yen", "typed ichiman nisen'en: n' before えん", "", -1, 1, deck::Kind::Number},
    {"num-yen-13800", "¥13,800", "いちまんさんぜんはっぴゃくえん", "", "13,800 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-19800", "¥19,800", "いちまんきゅうせんはっぴゃくえん", "", "19,800 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-20000", "¥20,000", "にまんえん", "", "20,000 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-30000", "¥30,000", "さんまんえん", "", "30,000 yen", "さんまん: nothing changes before まん", "", -1, 1, deck::Kind::Number},
    {"num-yen-48600", "¥48,600", "よんまんはっせんろっぴゃくえん", "", "48,600 yen", "", "", -1, 1, deck::Kind::Number},
    {"num-yen-100000", "¥100,000", "じゅうまんえん", "", "100,000 yen", "じゅうまん: ten times まん", "", -1, 1, deck::Kind::Number},
    {"num-yen-128000", "¥128,000", "じゅうにまんはっせんえん", "", "128,000 yen", "じゅうにまん, then はっせん", "", -1, 1, deck::Kind::Number},
    {"num-time-0005", "0:05", "れいじごふん", "ぜろじごふん|ごぜんれいじごふん", "0:05, just after midnight", "0 o'clock is れいじ", "", -1, 1, deck::Kind::Number},
    {"num-time-0111", "1:11", "いちじじゅういっぷん", "ごぜんいちじじゅういっぷん", "1:11 am", "じゅういっぷん, not じゅういちふん", "", -1, 1, deck::Kind::Number},
    {"num-time-0400", "4:00", "よじ", "ごぜんよじ", "4:00 am", "4 is よ before じ", "", -1, 1, deck::Kind::Number},
    {"num-time-0414", "4:14", "よじじゅうよんぷん", "よじじゅうよんふん|ごぜんよじじゅうよんぷん|ごぜんよじじゅうよんふん", "4:14 am", "よじ, but じゅうよんぷん", "", -1, 1, deck::Kind::Number},
    {"num-time-0520", "5:20", "ごじにじゅっぷん", "ごじにじっぷん|ごぜんごじにじゅっぷん|ごぜんごじにじっぷん", "5:20 am", "にじっぷん is also said", "", -1, 1, deck::Kind::Number},
    {"num-time-0601", "6:01", "ろくじいっぷん", "ごぜんろくじいっぷん", "6:01 am", "1 6 8 10 take っぷん", "", -1, 1, deck::Kind::Number},
    {"num-time-0700", "7:00", "しちじ", "ななじ|ごぜんしちじ|ごぜんななじ", "7:00 am", "ななじ is also said", "", -1, 1, deck::Kind::Number},
    {"num-time-0710", "7:10", "しちじじゅっぷん", "しちじじっぷん|ななじじゅっぷん|ななじじっぷん|ごぜんしちじじゅっぷん|ごぜんしちじじっぷん|ごぜんななじじゅっぷん|ごぜんななじじっぷん", "7:10 am", "じっぷん is also said", "", -1, 1, deck::Kind::Number},
    {"num-time-0803", "8:03", "はちじさんぷん", "ごぜんはちじさんぷん", "8:03 am", "3 takes ぷん: さんぷん", "", -1, 1, deck::Kind::Number},
    {"num-time-0856", "8:56", "はちじごじゅうろっぷん", "ごぜんはちじごじゅうろっぷん", "8:56 am", "ろっぷん, not ろくふん", "", -1, 1, deck::Kind::Number},
    {"num-time-0900", "9:00", "くじ", "ごぜんくじ", "9:00 am", "くじ, not きゅうじ", "", -1, 1, deck::Kind::Number},
    {"num-time-0904", "9:04", "くじよんぷん", "くじよんふん|ごぜんくじよんぷん|ごぜんくじよんふん", "9:04 am", "4 takes ぷん: よんぷん", "", -1, 1, deck::Kind::Number},
    {"num-time-0930", "9:30", "くじさんじゅっぷん", "くじさんじっぷん|くじはん|ごぜんくじさんじゅっぷん|ごぜんくじさんじっぷん|ごぜんくじはん", "9:30 am", "also くじはん, half past nine", "", -1, 1, deck::Kind::Number},
    {"num-time-1010", "10:10", "じゅうじじゅっぷん", "じゅうじじっぷん|ごぜんじゅうじじゅっぷん|ごぜんじゅうじじっぷん", "10:10 am", "じゅうじ, then じゅっぷん", "", -1, 1, deck::Kind::Number},
    {"num-time-1108", "11:08", "じゅういちじはっぷん", "じゅういちじはちふん|ごぜんじゅういちじはっぷん|ごぜんじゅういちじはちふん", "11:08 am", "はちふん is also said", "", -1, 1, deck::Kind::Number},
    {"num-time-1200", "12:00", "じゅうにじ", "ごごれいじ|ごぜんじゅうにじ", "12 noon", "with ごご it is ごごれいじ", "", -1, 1, deck::Kind::Number},
    {"num-time-1215", "12:15", "じゅうにじじゅうごふん", "ごごれいじじゅうごふん|ごごじゅうにじじゅうごふん", "12:15 pm", "ごごれいじ is the clearest after noon", "", -1, 1, deck::Kind::Number},
    {"num-time-1302", "13:02", "じゅうさんじにふん", "ごごいちじにふん", "1:02 pm", "also ごごいちじ, 1 pm", "", -1, 1, deck::Kind::Number},
    {"num-time-1400", "14:00", "じゅうよじ", "ごごにじ", "2:00 pm", "4 is よ before じ: じゅうよじ", "", -1, 1, deck::Kind::Number},
    {"num-time-1437", "14:37", "じゅうよじさんじゅうななふん", "じゅうよじさんじゅうしちふん|ごごにじさんじゅうななふん|ごごにじさんじゅうしちふん", "2:37 pm", "also ごごにじ, 2 pm", "", -1, 1, deck::Kind::Number},
    {"num-time-1550", "15:50", "じゅうごじごじゅっぷん", "じゅうごじごじっぷん|ごごさんじごじゅっぷん|ごごさんじごじっぷん", "3:50 pm", "also ごごさんじ, 3 pm", "", -1, 1, deck::Kind::Number},
    {"num-time-1644", "16:44", "じゅうろくじよんじゅうよんぷん", "じゅうろくじよんじゅうよんふん|ごごよじよんじゅうよんぷん|ごごよじよんじゅうよんふん", "4:44 pm", "also ごごよじ, 4 pm", "", -1, 1, deck::Kind::Number},
    {"num-time-1700", "17:00", "じゅうしちじ", "じゅうななじ|ごごごじ", "5:00 pm", "じゅうななじ is also said", "", -1, 1, deck::Kind::Number},
    {"num-time-1707", "17:07", "じゅうしちじななふん", "じゅうしちじしちふん|じゅうななじななふん|じゅうななじしちふん|ごごごじななふん|ごごごじしちふん", "5:07 pm", "しちふん is also said", "", -1, 1, deck::Kind::Number},
    {"num-time-1830", "18:30", "じゅうはちじさんじゅっぷん", "じゅうはちじさんじっぷん|じゅうはちじはん|ごごろくじさんじゅっぷん|ごごろくじさんじっぷん|ごごろくじはん", "6:30 pm", "also じゅうはちじはん, half past", "", -1, 1, deck::Kind::Number},
    {"num-time-1919", "19:19", "じゅうくじじゅうきゅうふん", "ごごしちじじゅうきゅうふん|ごごななじじゅうきゅうふん", "7:19 pm", "く before じ, きゅう before ふん", "", -1, 1, deck::Kind::Number},
    {"num-time-1945", "19:45", "じゅうくじよんじゅうごふん", "ごごしちじよんじゅうごふん|ごごななじよんじゅうごふん", "7:45 pm", "also ごごしちじ, 7 pm", "", -1, 1, deck::Kind::Number},
    {"num-time-2009", "20:09", "にじゅうじきゅうふん", "ごごはちじきゅうふん", "8:09 pm", "9 is きゅう before ふん", "", -1, 1, deck::Kind::Number},
    {"num-time-2115", "21:15", "にじゅういちじじゅうごふん", "ごごくじじゅうごふん", "9:15 pm", "also ごごくじ, 9 pm", "", -1, 1, deck::Kind::Number},
    {"num-time-2218", "22:18", "にじゅうにじじゅうはっぷん", "にじゅうにじじゅうはちふん|ごごじゅうじじゅうはっぷん|ごごじゅうじじゅうはちふん", "10:18 pm", "じゅうはっぷん: 8 takes っぷん", "", -1, 1, deck::Kind::Number},
    {"num-time-2340", "23:40", "にじゅうさんじよんじゅっぷん", "にじゅうさんじよんじっぷん|ごごじゅういちじよんじゅっぷん|ごごじゅういちじよんじっぷん", "11:40 pm", "also ごごじゅういちじ, 11 pm", "", -1, 1, deck::Kind::Number},
    {"num-date-0110", "1/10", "いちがつとおか", "", "10 January", "とおか: the 10th", "", -1, 1, deck::Kind::Number},
    {"num-date-0123", "1/23", "いちがつにじゅうさんにち", "", "23 January", "", "", -1, 1, deck::Kind::Number},
    {"num-date-0207", "2/7", "にがつなのか", "", "7 February", "なのか: the 7th", "", -1, 1, deck::Kind::Number},
    {"num-date-0306", "3/6", "さんがつむいか", "", "6 March", "むいか: the 6th", "", -1, 1, deck::Kind::Number},
    {"num-date-0327", "3/27", "さんがつにじゅうしちにち", "さんがつにじゅうななにち", "27 March", "にじゅうななにち is also said", "", -1, 1, deck::Kind::Number},
    {"num-date-0404", "4/4", "しがつよっか", "", "4 April", "しがつ, not よんがつ", "", -1, 1, deck::Kind::Number},
    {"num-date-0420", "4/20", "しがつはつか", "", "20 April", "はつか: the 20th", "", -1, 1, deck::Kind::Number},
    {"num-date-0509", "5/9", "ごがつここのか", "", "9 May", "ここのか: the 9th", "", -1, 1, deck::Kind::Number},
    {"num-date-0531", "5/31", "ごがつさんじゅういちにち", "", "31 May", "", "", -1, 1, deck::Kind::Number},
    {"num-date-0603", "6/3", "ろくがつみっか", "", "3 June", "みっか: the 3rd", "", -1, 1, deck::Kind::Number},
    {"num-date-0614", "6/14", "ろくがつじゅうよっか", "", "14 June", "the 14th and 24th end in よっか", "", -1, 1, deck::Kind::Number},
    {"num-date-0717", "7/17", "しちがつじゅうしちにち", "しちがつじゅうななにち|なながつじゅうしちにち|なながつじゅうななにち", "17 July", "なながつ is also said", "", -1, 1, deck::Kind::Number},
    {"num-date-0801", "8/1", "はちがつついたち", "", "1 August", "ついたち: the 1st", "", -1, 1, deck::Kind::Number},
    {"num-date-0829", "8/29", "はちがつにじゅうくにち", "", "29 August", "9 is く here: にじゅうくにち", "", -1, 1, deck::Kind::Number},
    {"num-date-0919", "9/19", "くがつじゅうくにち", "", "19 September", "くがつ, not きゅうがつ", "", -1, 1, deck::Kind::Number},
    {"num-date-1002", "10/2", "じゅうがつふつか", "", "2 October", "ふつか: the 2nd", "", -1, 1, deck::Kind::Number},
    {"num-date-1030", "10/30", "じゅうがつさんじゅうにち", "", "30 October", "", "", -1, 1, deck::Kind::Number},
    {"num-date-1105", "11/5", "じゅういちがついつか", "", "5 November", "いつか: the 5th", "", -1, 1, deck::Kind::Number},
    {"num-date-1124", "11/24", "じゅういちがつにじゅうよっか", "", "24 November", "the 14th and 24th end in よっか", "", -1, 1, deck::Kind::Number},
    {"num-date-1208", "12/8", "じゅうにがつようか", "", "8 December", "ようか: the 8th. よっか is the 4th", "", -1, 1, deck::Kind::Number},
};

const deck::Item kItems_counters[] = {
    {"count-tsu-1", "これ × 1", "ひとつ", "いっこ", "one of these", "つ: for any thing, 1 to 10 only", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-2", "これ × 2", "ふたつ", "にこ", "two of these", "つ: for any thing, 1 to 10 only", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-3", "これ × 3", "みっつ", "さんこ", "three of these", "small っ: みっつ よっつ むっつ やっつ", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-4", "これ × 4", "よっつ", "よんこ", "four of these", "small っ: みっつ よっつ むっつ やっつ", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-5", "これ × 5", "いつつ", "ごこ", "five of these", "つ: for any thing, 1 to 10 only", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-6", "これ × 6", "むっつ", "ろっこ", "six of these", "small っ: みっつ よっつ むっつ やっつ", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-7", "これ × 7", "ななつ", "ななこ|しちこ", "seven of these", "つ: for any thing, 1 to 10 only", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-8", "これ × 8", "やっつ", "はっこ|はちこ", "eight of these", "small っ: みっつ よっつ むっつ やっつ", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-9", "これ × 9", "ここのつ", "きゅうこ", "nine of these", "つ: for any thing, 1 to 10 only", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-10", "これ × 10", "とお", "じゅっこ|じっこ", "ten of these", "とお: no つ. From 11: じゅういち", "", -1, 1, deck::Kind::Counter},
    {"count-tsu-ikutsu", "これ × ?", "いくつ", "なんこ", "how many of these?", "いくつ: how many, of any thing", "", -1, 1, deck::Kind::Counter},
    {"count-nin-1", "おとな × 1", "ひとり", "いちめい", "one adult", "人: 1 ひとり 2 ふたり, then にん", "", -1, 1, deck::Kind::Counter},
    {"count-nin-2", "おとな × 2", "ふたり", "にめい", "two adults", "人: 1 ひとり 2 ふたり, then にん", "", -1, 1, deck::Kind::Counter},
    {"count-nin-3", "こども × 3", "さんにん", "さんめい", "three children", "from 3: the number plus にん (人)", "", -1, 1, deck::Kind::Counter},
    {"count-nin-4", "おとな × 4", "よにん", "よんめい", "four adults", "4 is よにん, not よんにん or しにん", "", -1, 1, deck::Kind::Counter},
    {"count-nin-5", "こども × 5", "ごにん", "ごめい", "five children", "from 3: the number plus にん (人)", "", -1, 1, deck::Kind::Counter},
    {"count-nin-7", "ひと × 7", "しちにん", "ななにん|ななめい|しちめい", "seven people", "7 is しちにん or ななにん", "", -1, 1, deck::Kind::Counter},
    {"count-nin-9", "ひと × 9", "きゅうにん", "くにん|きゅうめい", "nine people", "9 is きゅうにん or くにん", "", -1, 1, deck::Kind::Counter},
    {"count-nin-10", "ひと × 10", "じゅうにん", "じゅうめい", "ten people", "from 3: the number plus にん (人)", "", -1, 1, deck::Kind::Counter},
    {"count-nin-nan", "ひと × ?", "なんにん", "なんめい", "how many people?", "なんにん (何人). Formal: なんめい", "", -1, 1, deck::Kind::Counter},
    {"count-mei-1", "おきゃくさま × 1 (formal)", "いちめい", "いちめいさま|おひとりさま", "one guest (formal)", "名 めい: polite count of guests", "", -1, 1, deck::Kind::Counter},
    {"count-mei-2", "おきゃくさま × 2 (formal)", "にめい", "にめいさま", "two guests (formal)", "staff ask なんめいさまですか", "", -1, 1, deck::Kind::Counter},
    {"count-mei-3", "おきゃくさま × 3 (formal)", "さんめい", "さんめいさま", "three guests (formal)", "名 めい: polite count of guests", "", -1, 1, deck::Kind::Counter},
    {"count-mei-4", "おきゃくさま × 4 (formal)", "よんめい", "よんめいさま", "four guests (formal)", "staff ask なんめいさまですか", "", -1, 1, deck::Kind::Counter},
    {"count-mei-10", "おきゃくさま × 10 (formal)", "じゅうめい", "じゅうめいさま", "ten guests (formal)", "名 めい: polite count of guests", "", -1, 1, deck::Kind::Counter},
    {"count-mei-nan", "おきゃくさま × ? (formal)", "なんめい", "なんめいさま", "formal: how many guests?", "staff ask なんめいさまですか", "", -1, 1, deck::Kind::Counter},
    {"count-hon-1", "かさ × 1", "いっぽん", "", "one umbrella", "本: 1 いっぽん 3 さんぼん 6 ろっぽん", "", -1, 1, deck::Kind::Counter},
    {"count-hon-2", "ビール (びん) × 2", "にほん", "ふたつ", "two bottles of beer", "本 ほん: long thin things, bottles", "", -1, 1, deck::Kind::Counter},
    {"count-hon-3", "ペン × 3", "さんぼん", "", "three pens", "本: 1 いっぽん 3 さんぼん 6 ろっぽん", "", -1, 1, deck::Kind::Counter},
    {"count-hon-4", "バナナ × 4", "よんほん", "しほん|よっつ", "four bananas", "4 is よんほん: no sound change", "", -1, 1, deck::Kind::Counter},
    {"count-hon-5", "やきとり × 5", "ごほん", "いつつ", "five yakitori skewers", "本 ほん: long thin things, bottles", "", -1, 1, deck::Kind::Counter},
    {"count-hon-6", "ビール (びん) × 6", "ろっぽん", "むっつ", "six bottles of beer", "本: 1 いっぽん 3 さんぼん 6 ろっぽん", "", -1, 1, deck::Kind::Counter},
    {"count-hon-8", "かさ × 8", "はっぽん", "はちほん", "eight umbrellas", "本: 8 はっぽん 10 じゅっぽん", "", -1, 1, deck::Kind::Counter},
    {"count-hon-10", "ペン × 10", "じゅっぽん", "じっぽん", "ten pens", "10 is じゅっぽん or じっぽん", "", -1, 1, deck::Kind::Counter},
    {"count-hon-nan", "ビール (びん) × ?", "なんぼん", "いくつ", "how many bottles of beer?", "なん takes ぼん, as 3 does: なんぼん", "", -1, 1, deck::Kind::Counter},
    {"count-hai-1", "みず (コップ) × 1", "いっぱい", "ひとつ", "one glass of water", "杯: 1 いっぱい 3 さんばい 6 ろっぱい", "", -1, 1, deck::Kind::Counter},
    {"count-hai-2", "ごはん (ちゃわん) × 2", "にはい", "ふたつ", "two bowls of rice", "杯 はい: full glasses, cups, bowls", "", -1, 1, deck::Kind::Counter},
    {"count-hai-3", "ビール (グラス) × 3", "さんばい", "みっつ", "three glasses of beer", "杯: 1 いっぱい 3 さんばい 6 ろっぱい", "", -1, 1, deck::Kind::Counter},
    {"count-hai-4", "コーヒー (カップ) × 4", "よんはい", "よっつ", "four cups of coffee", "4 is よんはい: no sound change", "", -1, 1, deck::Kind::Counter},
    {"count-hai-6", "ビール (ジョッキ) × 6", "ろっぱい", "むっつ", "six mugs of beer", "杯: 1 いっぱい 3 さんばい 6 ろっぱい", "", -1, 1, deck::Kind::Counter},
    {"count-hai-8", "ラーメン × 8", "はっぱい", "はちはい|やっつ", "eight bowls of ramen", "杯: 8 はっぱい 10 じゅっぱい", "", -1, 1, deck::Kind::Counter},
    {"count-hai-10", "みず (コップ) × 10", "じゅっぱい", "じっぱい|とお", "ten glasses of water", "10 is じゅっぱい or じっぱい", "", -1, 1, deck::Kind::Counter},
    {"count-hai-nan", "ビール (グラス) × ?", "なんばい", "いくつ", "how many glasses of beer?", "なん takes ばい, as 3 does: なんばい", "", -1, 1, deck::Kind::Counter},
    {"count-mai-1", "きっぷ × 1", "いちまい", "", "one ticket", "枚 まい: flat things. No sound change", "", -1, 1, deck::Kind::Counter},
    {"count-mai-2", "きっぷ × 2", "にまい", "", "two tickets", "枚: tickets, plates, shirts, paper", "", -1, 1, deck::Kind::Counter},
    {"count-mai-3", "シャツ × 3", "さんまい", "", "three shirts", "枚 まい: flat things. No sound change", "", -1, 1, deck::Kind::Counter},
    {"count-mai-4", "さら × 4", "よんまい", "", "four plates", "枚: tickets, plates, shirts, paper", "", -1, 1, deck::Kind::Counter},
    {"count-mai-7", "タオル × 7", "ななまい", "しちまい", "seven towels", "7 is ななまい or しちまい", "", -1, 1, deck::Kind::Counter},
    {"count-mai-10", "はがき × 10", "じゅうまい", "", "ten postcards", "枚 まい: flat things. No sound change", "", -1, 1, deck::Kind::Counter},
    {"count-mai-nan", "きっぷ × ?", "なんまい", "", "how many tickets?", "枚 まい: flat things. No sound change", "", -1, 1, deck::Kind::Counter},
    {"count-ko-1", "りんご × 1", "いっこ", "ひとつ", "one apple", "個: 1 いっこ 6 ろっこ 8 はっこ", "", -1, 1, deck::Kind::Counter},
    {"count-ko-2", "たまご × 2", "にこ", "ふたつ", "two eggs", "個 こ: small things you can hold", "", -1, 1, deck::Kind::Counter},
    {"count-ko-3", "おにぎり × 3", "さんこ", "みっつ", "three rice balls", "個 こ: small things you can hold", "", -1, 1, deck::Kind::Counter},
    {"count-ko-6", "たまご × 6", "ろっこ", "むっつ", "six eggs", "個: 1 いっこ 6 ろっこ 8 はっこ", "", -1, 1, deck::Kind::Counter},
    {"count-ko-8", "りんご × 8", "はっこ", "はちこ|やっつ", "eight apples", "個: 1 いっこ 6 ろっこ 8 はっこ", "", -1, 1, deck::Kind::Counter},
    {"count-ko-10", "みかん × 10", "じゅっこ", "じっこ|とお", "ten mandarins", "10 is じゅっこ or じっこ", "", -1, 1, deck::Kind::Counter},
    {"count-ko-nan", "りんご × ?", "なんこ", "いくつ", "how many apples?", "なんこ (何個), or いくつ", "", -1, 1, deck::Kind::Counter},
    {"count-haku-1", "1 night (hotel)", "いっぱく", "", "a stay of one night", "泊: 1 いっぱく 3 さんぱく 6 ろっぱく", "", -1, 1, deck::Kind::Counter},
    {"count-haku-2", "2 nights (hotel)", "にはく", "", "a stay of two nights", "泊 はく: nights of a stay", "", -1, 1, deck::Kind::Counter},
    {"count-haku-3", "3 nights (hotel)", "さんぱく", "", "a stay of three nights", "泊: 1 いっぱく 3 さんぱく 6 ろっぱく", "", -1, 1, deck::Kind::Counter},
    {"count-haku-4", "4 nights (hotel)", "よんぱく", "よんはく", "a stay of four nights", "4 is よんぱく or よんはく", "", -1, 1, deck::Kind::Counter},
    {"count-haku-6", "6 nights (hotel)", "ろっぱく", "", "a stay of six nights", "泊: 1 いっぱく 3 さんぱく 6 ろっぱく", "", -1, 1, deck::Kind::Counter},
    {"count-haku-8", "8 nights (hotel)", "はっぱく", "はちはく", "a stay of eight nights", "泊: 8 はっぱく 10 じゅっぱく", "", -1, 1, deck::Kind::Counter},
    {"count-haku-10", "10 nights (hotel)", "じゅっぱく", "じっぱく", "a stay of ten nights", "10 is じゅっぱく or じっぱく", "", -1, 1, deck::Kind::Counter},
    {"count-kai-1", "1F", "いっかい", "", "floor 1, at street level", "Japan counts street level as 1F", "", -1, 1, deck::Kind::Counter},
    {"count-kai-2", "2F", "にかい", "", "floor 2", "階: 1 いっかい 3 さんがい 6 ろっかい", "", -1, 1, deck::Kind::Counter},
    {"count-kai-3", "3F", "さんがい", "さんかい", "floor 3", "3 is さんがい. さんかい is also heard", "", -1, 1, deck::Kind::Counter},
    {"count-kai-4", "4F", "よんかい", "", "floor 4", "階 かい: floors of a building", "", -1, 1, deck::Kind::Counter},
    {"count-kai-6", "6F", "ろっかい", "", "floor 6", "階: 1 いっかい 3 さんがい 6 ろっかい", "", -1, 1, deck::Kind::Counter},
    {"count-kai-8", "8F", "はっかい", "はちかい", "floor 8", "階: 8 はっかい 10 じゅっかい", "", -1, 1, deck::Kind::Counter},
    {"count-kai-10", "10F", "じゅっかい", "じっかい", "floor 10", "10 is じゅっかい or じっかい", "", -1, 1, deck::Kind::Counter},
    {"count-kai-b1", "B1", "ちかいっかい", "", "basement floor 1", "地下 ちか: basement. B2 is ちかにかい", "", -1, 1, deck::Kind::Counter},
    {"count-kai-nan", "?F", "なんがい", "なんかい", "which floor?", "なんがい, as 3 is さんがい", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-1", "platform 1", "いちばんせん", "", "platform 1 (track no. 1)", "番線 ばんせん: platform, track", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-2", "platform 2", "にばんせん", "", "platform 2 (track no. 2)", "番線 ばんせん: platform, track", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-3", "platform 3", "さんばんせん", "", "platform 3 (track no. 3)", "番線 ばんせん: platform, track", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-4", "platform 4", "よんばんせん", "", "platform 4 (track no. 4)", "4 is よんばんせん", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-7", "platform 7", "ななばんせん", "しちばんせん", "platform 7 (track no. 7)", "7 is ななばんせん or しちばんせん", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-9", "platform 9", "きゅうばんせん", "", "platform 9 (track no. 9)", "9 is きゅうばんせん", "", -1, 1, deck::Kind::Counter},
    {"count-bansen-nan", "platform ?", "なんばんせん", "", "which platform?", "asked as なんばんせんですか", "", -1, 1, deck::Kind::Counter},
    {"count-gousha-1", "car 1", "いちごうしゃ", "", "car 1 of a train", "号車 ごうしゃ: car, as on the ticket", "", -1, 1, deck::Kind::Counter},
    {"count-gousha-4", "car 4", "よんごうしゃ", "", "car 4 of a train", "4 is よんごうしゃ", "", -1, 1, deck::Kind::Counter},
    {"count-gousha-9", "car 9", "きゅうごうしゃ", "", "car 9 of a train", "9 is きゅうごうしゃ", "", -1, 1, deck::Kind::Counter},
    {"count-fun-1", "9:01 (minutes only)", "いっぷん", "", "1 minute past", "分: 1 いっぷん 3 さんぷん 4 よんぷん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-2", "9:02 (minutes only)", "にふん", "", "2 minutes past", "ふん after 2, 5, 7 and 9", "", -1, 1, deck::Kind::Counter},
    {"count-fun-3", "9:03 (minutes only)", "さんぷん", "", "3 minutes past", "分: 1 いっぷん 3 さんぷん 4 よんぷん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-4", "9:04 (minutes only)", "よんぷん", "よんふん", "4 minutes past", "分: 1 いっぷん 3 さんぷん 4 よんぷん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-5", "9:05 (minutes only)", "ごふん", "", "5 minutes past", "ふん after 2, 5, 7 and 9", "", -1, 1, deck::Kind::Counter},
    {"count-fun-6", "9:06 (minutes only)", "ろっぷん", "", "6 minutes past", "分: 6 ろっぷん 8 はっぷん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-7", "9:07 (minutes only)", "ななふん", "しちふん", "7 minutes past", "7 is ななふん or しちふん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-8", "9:08 (minutes only)", "はっぷん", "はちふん", "8 minutes past", "分: 6 ろっぷん 8 はっぷん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-9", "9:09 (minutes only)", "きゅうふん", "", "9 minutes past", "ふん after 2, 5, 7 and 9", "", -1, 1, deck::Kind::Counter},
    {"count-fun-10", "9:10 (minutes only)", "じゅっぷん", "じっぷん", "10 minutes past", "10 is じゅっぷん or じっぷん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-15", "9:15 (minutes only)", "じゅうごふん", "", "15 minutes past", "the last digit decides: 5 is ごふん", "", -1, 1, deck::Kind::Counter},
    {"count-fun-30", "9:30 (minutes only)", "さんじゅっぷん", "さんじっぷん|はん", "30 minutes past", "9:30 is also くじはん (半)", "", -1, 1, deck::Kind::Counter},
    {"count-fun-nan", "9:?\? (minutes only)", "なんぷん", "", "how many minutes past?", "なん takes ぷん, as 3 does: なんぷん", "", -1, 1, deck::Kind::Counter},
    {"count-ji-1", "1 o'clock", "いちじ", "", "one o'clock (1:00 or 13:00)", "時: 4 よじ 7 しちじ 9 くじ", "", -1, 1, deck::Kind::Counter},
    {"count-ji-4", "4 o'clock", "よじ", "", "four o'clock (4:00 or 16:00)", "4 is よじ, not よんじ or しじ", "", -1, 1, deck::Kind::Counter},
    {"count-ji-6", "6 o'clock", "ろくじ", "", "six o'clock (6:00 or 18:00)", "時: 4 よじ 7 しちじ 9 くじ", "", -1, 1, deck::Kind::Counter},
    {"count-ji-7", "7 o'clock", "しちじ", "ななじ", "seven o'clock (7:00 or 19:00)", "7 is しちじ. ななじ is also heard", "", -1, 1, deck::Kind::Counter},
    {"count-ji-9", "9 o'clock", "くじ", "", "nine o'clock (9:00 or 21:00)", "9 is くじ, not きゅうじ", "", -1, 1, deck::Kind::Counter},
    {"count-ji-10", "10 o'clock", "じゅうじ", "", "ten o'clock (10:00 or 22:00)", "時: 4 よじ 7 しちじ 9 くじ", "", -1, 1, deck::Kind::Counter},
    {"count-ji-12", "12 o'clock", "じゅうにじ", "", "twelve o'clock (noon, midnight)", "時: 4 よじ 7 しちじ 9 くじ", "", -1, 1, deck::Kind::Counter},
    {"count-ji-nan", "? o'clock", "なんじ", "", "what time?", "asked as いま なんじですか", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-1", "1 hour", "いちじかん", "", "for one hour", "時間 じかん: hours, how long", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-2", "2 hours", "にじかん", "", "for two hours", "時間 じかん: hours, how long", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-4", "4 hours", "よじかん", "", "for four hours", "時間: 4 よじかん 9 くじかん", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-7", "7 hours", "しちじかん", "ななじかん", "for seven hours", "7 is しちじかん or ななじかん", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-9", "9 hours", "くじかん", "", "for nine hours", "時間: 4 よじかん 9 くじかん", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-1-5", "1.5 hours", "いちじかんはん", "", "for an hour and a half", "半 はん: and a half", "", -1, 1, deck::Kind::Counter},
    {"count-jikan-nan", "? hours", "なんじかん", "", "how many hours?", "時間 じかん: hours, how long", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-1", "the 1st (date)", "ついたち", "いっぴ", "the 1st of the month", "日: 1 ついたち 2 ふつか 3 みっか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-2", "the 2nd (date)", "ふつか", "", "the 2nd of the month", "日: 1 ついたち 2 ふつか 3 みっか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-3", "the 3rd (date)", "みっか", "", "the 3rd of the month", "日: 1 ついたち 2 ふつか 3 みっか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-4", "the 4th (date)", "よっか", "", "the 4th of the month", "4 よっか and 8 ようか sound close", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-5", "the 5th (date)", "いつか", "", "the 5th of the month", "日: 4 よっか 5 いつか 6 むいか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-6", "the 6th (date)", "むいか", "", "the 6th of the month", "日: 4 よっか 5 いつか 6 むいか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-7", "the 7th (date)", "なのか", "", "the 7th of the month", "日: 7 なのか 8 ようか 9 ここのか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-8", "the 8th (date)", "ようか", "", "the 8th of the month", "4 よっか and 8 ようか sound close", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-9", "the 9th (date)", "ここのか", "", "the 9th of the month", "日: 7 なのか 8 ようか 9 ここのか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-10", "the 10th (date)", "とおか", "", "the 10th of the month", "10 とおか 14 じゅうよっか 20 はつか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-11", "the 11th (date)", "じゅういちにち", "", "the 11th of the month", "11 to 31: にち, but not 14 20 24", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-14", "the 14th (date)", "じゅうよっか", "", "the 14th of the month", "14 じゅうよっか 24 にじゅうよっか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-17", "the 17th (date)", "じゅうしちにち", "じゅうななにち", "the 17th of the month", "17 じゅうしちにち 19 じゅうくにち", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-19", "the 19th (date)", "じゅうくにち", "", "the 19th of the month", "17 じゅうしちにち 19 じゅうくにち", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-20", "the 20th (date)", "はつか", "", "the 20th of the month", "10 とおか 14 じゅうよっか 20 はつか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-24", "the 24th (date)", "にじゅうよっか", "", "the 24th of the month", "14 じゅうよっか 24 にじゅうよっか", "", -1, 1, deck::Kind::Counter},
    {"count-nichi-nan", "the ?th (date)", "なんにち", "", "which day of the month?", "なんにち asks for the date", "", -1, 1, deck::Kind::Counter},
    {"count-nichikan-1", "1 day (how long)", "いちにち", "いちにちかん", "for one day", "1 day is いちにち, not ついたち", "", -1, 1, deck::Kind::Counter},
    {"count-nichikan-2", "2 days (how long)", "ふつかかん", "ふつか", "for two days", "日間: the day word plus かん (間)", "", -1, 1, deck::Kind::Counter},
    {"count-nichikan-3", "3 days (how long)", "みっかかん", "みっか", "for three days", "日間: the day word plus かん (間)", "", -1, 1, deck::Kind::Counter},
    {"count-nichikan-7", "7 days (how long)", "なのかかん", "なのか|いっしゅうかん", "for seven days", "日間: the day word plus かん (間)", "", -1, 1, deck::Kind::Counter},
    {"count-nichikan-10", "10 days (how long)", "とおかかん", "とおか", "for ten days", "日間: the day word plus かん (間)", "", -1, 1, deck::Kind::Counter},
    {"count-nichikan-nan", "? days (how long)", "なんにち", "", "how many days?", "なんにち also asks how many days", "", -1, 1, deck::Kind::Counter},
    {"count-shuukan-1", "1 week", "いっしゅうかん", "", "for one week", "週間: 1 いっしゅうかん 2 にしゅうかん", "", -1, 1, deck::Kind::Counter},
    {"count-shuukan-2", "2 weeks", "にしゅうかん", "", "for two weeks", "週間: 1 いっしゅうかん 2 にしゅうかん", "", -1, 1, deck::Kind::Counter},
    {"count-ninmae-1", "1 serving (food)", "いちにんまえ", "ひとりまえ", "one serving, a portion for one", "人前 にんまえ: portions on a menu", "", -1, 1, deck::Kind::Counter},
    {"count-ninmae-2", "2 servings (food)", "ににんまえ", "", "two servings", "人前 にんまえ: portions on a menu", "", -1, 1, deck::Kind::Counter},
};

const deck::Item kItems_katakana_words[] = {
    {"kata-menyuu", "メニュー", "メニュー", "", "menu", "", "", 1, 1, deck::Kind::Word},
    {"kata-resutoran", "レストラン", "レストラン", "", "restaurant", "mostly Western-style food", "", 1, 1, deck::Kind::Word},
    {"kata-kafe", "カフェ", "カフェ", "", "cafe", "フェ is typed fe", "", 1, 1, deck::Kind::Word},
    {"kata-koohii", "コーヒー", "コーヒー", "", "coffee", "two long marks: typed ko-hi-", "", 3, 1, deck::Kind::Word},
    {"kata-biiru", "ビール", "ビール", "", "beer", "without the long mark: ビル, building", "", 1, 1, deck::Kind::Word},
    {"kata-biru", "ビル", "ビル", "", "multi-storey building", "not a bill, and not ビール (beer)", "", 1, 1, deck::Kind::Word},
    {"kata-wain", "ワイン", "ワイン", "", "wine", "ワ, not ウ or フ", "", 1, 1, deck::Kind::Word},
    {"kata-uisukii", "ウイスキー", "ウイスキー", "", "whisky", "ウ, not ワ or フ", "", 3, 1, deck::Kind::Word},
    {"kata-haibooru", "ハイボール", "ハイボール", "", "whisky and soda", "", "", 3, 1, deck::Kind::Word},
    {"kata-sawaa", "サワー", "サワー", "", "sour cocktail, often fizzy", "ワ, not ウ or フ", "", 1, 1, deck::Kind::Word},
    {"kata-nonarukooru", "ノンアルコール", "ノンアルコール", "", "alcohol-free", "ノ and ン in one word", "", -1, 1, deck::Kind::Word},
    {"kata-juusu", "ジュース", "ジュース", "", "soft drink; juice", "any sweet soft drink, not only juice", "", 1, 1, deck::Kind::Word},
    {"kata-saidaa", "サイダー", "サイダー", "", "sweet fizzy drink", "not cider: a soft drink", "", 1, 1, deck::Kind::Word},
    {"kata-kafeore", "カフェオレ", "カフェオレ", "", "cafe au lait", "フェ is typed fe", "", 0, 1, deck::Kind::Word},
    {"kata-kapuchiino", "カプチーノ", "カプチーノ", "", "cappuccino", "ノ, not ソ or ン", "", 3, 1, deck::Kind::Word},
    {"kata-esupuresso", "エスプレッソ", "エスプレッソ", "", "espresso", "ソ, not ン or ノ", "", 4, 1, deck::Kind::Word},
    {"kata-afutanuunthii", "アフタヌーンティー", "アフタヌーンティー", "", "afternoon tea", "ヌ, not ス; ティ is typed thi", "", -1, 1, deck::Kind::Word},
    {"kata-hotto", "ホット", "ホット", "", "hot; hot coffee", "said alone in a cafe: hot coffee", "", 1, 1, deck::Kind::Word},
    {"kata-aisu", "アイス", "アイス", "", "ice cream; iced (drink)", "short for アイスクリーム; also iced", "", 1, 1, deck::Kind::Word},
    {"kata-aisukoohii", "アイスコーヒー", "アイスコーヒー", "", "iced coffee", "", "", 6, 1, deck::Kind::Word},
    {"kata-amerikan", "アメリカン", "アメリカン", "", "weak drip coffee", "on a menu: not an American", "", 2, 1, deck::Kind::Word},
    {"kata-mooningu", "モーニング", "モーニング", "", "breakfast set", "in a cafe: not just 'morning'", "", 1, 1, deck::Kind::Word},
    {"kata-mooningusetto", "モーニングセット", "モーニングセット", "", "breakfast set", "often a drink and toast", "", -1, 1, deck::Kind::Word},
    {"kata-dorinku", "ドリンク", "ドリンク", "", "drink", "ク, not ケ or タ", "", 2, 1, deck::Kind::Word},
    {"kata-dorinkubaa", "ドリンクバー", "ドリンクバー", "", "self-service drinks", "made in Japan from 'drink bar'", "", -1, 1, deck::Kind::Word},
    {"kata-ranchi", "ランチ", "ランチ", "", "lunch; lunch set", "チ, not テ", "", 1, 1, deck::Kind::Word},
    {"kata-dhinaa", "ディナー", "ディナー", "", "dinner", "ディ is typed dhi", "", 1, 1, deck::Kind::Word},
    {"kata-setto", "セット", "セット", "", "set; combo", "", "", 1, 1, deck::Kind::Word},
    {"kata-koosu", "コース", "コース", "", "course meal; course; route", "on a menu: a meal of several courses", "", 1, 1, deck::Kind::Word},
    {"kata-baikingu", "バイキング", "バイキング", "", "buffet", "not a Viking: a buffet meal", "", 1, 1, deck::Kind::Word},
    {"kata-byuffe", "ビュッフェ", "ビュッフェ", "", "buffet", "like バイキング; フェ is typed fe", "", 1, 1, deck::Kind::Word},
    {"kata-teikuauto", "テイクアウト", "テイクアウト", "", "takeaway", "テ, not チ; ク, not ケ", "", 4, 1, deck::Kind::Word},
    {"kata-iitoin", "イートイン", "イートイン", "", "eating in (at the shop)", "the opposite of テイクアウト", "", -1, 1, deck::Kind::Word},
    {"kata-rasutooodaa", "ラストオーダー", "ラストオーダー", "", "last orders", "", "", -1, 1, deck::Kind::Word},
    {"kata-serufu", "セルフ", "セルフ", "", "self-service", "short for セルフサービス", "", 1, 1, deck::Kind::Word},
    {"kata-saabisu", "サービス", "サービス", "", "free extra; discount; service", "often means free, not just service", "", 1, 1, deck::Kind::Word},
    {"kata-pan", "パン", "パン", "", "bread", "not a pan: the word is Portuguese", "", 1, 1, deck::Kind::Word},
    {"kata-sandoitchi", "サンドイッチ", "サンドイッチ", "", "sandwich", "small ッ: typed sandoitchi", "", 4, 1, deck::Kind::Word},
    {"kata-sando", "サンド", "サンド", "", "sandwich (short form)", "not sand: short for サンドイッチ", "", 1, 1, deck::Kind::Word},
    {"kata-chiizu", "チーズ", "チーズ", "", "cheese", "チ, not テ", "", 1, 1, deck::Kind::Word},
    {"kata-sooseeji", "ソーセージ", "ソーセージ", "", "sausage", "ソ, not ン", "", 1, 1, deck::Kind::Word},
    {"kata-suupu", "スープ", "スープ", "", "soup", "ス, not ヌ", "", 1, 1, deck::Kind::Word},
    {"kata-raisu", "ライス", "ライス", "", "rice (served on a plate)", "", "", 1, 1, deck::Kind::Word},
    {"kata-karee", "カレー", "カレー", "", "curry; curry and rice", "also short for カレーライス", "", 0, 1, deck::Kind::Word},
    {"kata-sarada", "サラダ", "サラダ", "", "salad", "", "", 1, 1, deck::Kind::Word},
    {"kata-katsu", "カツ", "カツ", "", "breaded fried cutlet", "ツ, not シ", "", 1, 1, deck::Kind::Word},
    {"kata-hanbaagaa", "ハンバーガー", "ハンバーガー", "", "hamburger (in a bun)", "", "", 3, 1, deck::Kind::Word},
    {"kata-hanbaagu", "ハンバーグ", "ハンバーグ", "", "hamburger steak", "not a burger: that is ハンバーガー", "", 3, 1, deck::Kind::Word},
    {"kata-suteeki", "ステーキ", "ステーキ", "", "steak", "テ, not チ", "", 2, 1, deck::Kind::Word},
    {"kata-omuraisu", "オムライス", "オムライス", "", "fried rice in an omelette", "", "", 3, 1, deck::Kind::Word},
    {"kata-naporitan", "ナポリタン", "ナポリタン", "", "spaghetti with ketchup", "a Japanese dish", "", 2, 1, deck::Kind::Word},
    {"kata-korokke", "コロッケ", "コロッケ", "", "croquette", "ケ, not ク", "", 1, 1, deck::Kind::Word},
    {"kata-furaidopoteto", "フライドポテト", "フライドポテト", "", "chips; French fries", "from 'fried potato'", "", -1, 1, deck::Kind::Word},
    {"kata-raamen", "ラーメン", "ラーメン", "", "ramen", "", "", 1, 1, deck::Kind::Word},
    {"kata-nuudoru", "ヌードル", "ヌードル", "", "noodles", "ヌ, not ス", "", 1, 1, deck::Kind::Word},
    {"kata-mayoneezu", "マヨネーズ", "マヨネーズ", "", "mayonnaise", "ヨ, not コ or ユ", "", 3, 1, deck::Kind::Word},
    {"kata-kechappu", "ケチャップ", "ケチャップ", "", "ketchup", "ケ, not ク; チ, not テ", "", 2, 1, deck::Kind::Word},
    {"kata-soosu", "ソース", "ソース", "", "sauce; Worcestershire sauce", "ソ, not ン", "", 1, 1, deck::Kind::Word},
    {"kata-doresshingu", "ドレッシング", "ドレッシング", "", "salad dressing", "シ, not ツ", "", 2, 1, deck::Kind::Word},
    {"kata-dezaato", "デザート", "デザート", "", "dessert", "", "", 2, 1, deck::Kind::Word},
    {"kata-suiitsu", "スイーツ", "スイーツ", "", "sweets; desserts", "ツ, not シ", "", -1, 1, deck::Kind::Word},
    {"kata-keeki", "ケーキ", "ケーキ", "", "cake", "ケ, not ク or タ", "", 1, 1, deck::Kind::Word},
    {"kata-hottokeeki", "ホットケーキ", "ホットケーキ", "", "pancake", "an American-style pancake", "", 4, 1, deck::Kind::Word},
    {"kata-shuukuriimu", "シュークリーム", "シュークリーム", "", "cream puff", "not shoe cream: from French 'chou'", "", 4, 1, deck::Kind::Word},
    {"kata-sofutokuriimu", "ソフトクリーム", "ソフトクリーム", "", "soft-serve ice cream", "made in Japan from 'soft cream'", "", 5, 1, deck::Kind::Word},
    {"kata-chokoreeto", "チョコレート", "チョコレート", "", "chocolate", "", "", 3, 1, deck::Kind::Word},
    {"kata-yooguruto", "ヨーグルト", "ヨーグルト", "", "yoghurt", "ヨ, not コ or ユ", "", 3, 1, deck::Kind::Word},
    {"kata-furuutsu", "フルーツ", "フルーツ", "", "fruit", "フ, not ウ or ワ; ツ, not シ", "", 2, 1, deck::Kind::Word},
    {"kata-kyabetsu", "キャベツ", "キャベツ", "", "cabbage", "", "", 1, 1, deck::Kind::Word},
    {"kata-piiman", "ピーマン", "ピーマン", "", "green pepper", "from French 'piment'", "", 1, 1, deck::Kind::Word},
    {"kata-supuun", "スプーン", "スプーン", "", "spoon", "ス, not ヌ", "", 2, 1, deck::Kind::Word},
    {"kata-arerugii", "アレルギー", "アレルギー", "", "allergy", "from German 'Allergie'", "", 2, 1, deck::Kind::Word},
    {"kata-koppu", "コップ", "コップ", "", "drinking glass; tumbler", "a glass; カップ is a cup", "", 0, 1, deck::Kind::Word},
    {"kata-kauntaa", "カウンター", "カウンター", "", "counter; bar", "タ, not ク or ケ", "", 0, 1, deck::Kind::Word},
    {"kata-teeburu", "テーブル", "テーブル", "", "table", "テ, not チ", "", 0, 1, deck::Kind::Word},
    {"kata-konbini", "コンビニ", "コンビニ", "", "convenience store", "short for コンビニエンスストア", "", 0, 1, deck::Kind::Word},
    {"kata-suupaa", "スーパー", "スーパー", "", "supermarket", "alone: a supermarket, not 'super'", "", 1, 1, deck::Kind::Word},
    {"kata-depaato", "デパート", "デパート", "", "department store", "short for デパートメントストア", "", 2, 1, deck::Kind::Word},
    {"kata-doraggusutoa", "ドラッグストア", "ドラッグストア", "", "pharmacy; drugstore", "", "", 6, 1, deck::Kind::Word},
    {"kata-reji", "レジ", "レジ", "", "till; checkout", "short for レジスター", "", 1, 1, deck::Kind::Word},
    {"kata-serufureji", "セルフレジ", "セルフレジ", "", "self-checkout", "made in Japan: セルフ and レジ", "", -1, 1, deck::Kind::Word},
    {"kata-renji", "レンジ", "レンジ", "", "microwave oven; cooker", "not レジ, the till", "", 1, 1, deck::Kind::Word},
    {"kata-reshiito", "レシート", "レシート", "", "receipt", "", "", 2, 1, deck::Kind::Word},
    {"kata-kaado", "カード", "カード", "", "card; credit or debit card", "", "", 1, 1, deck::Kind::Word},
    {"kata-kurejittokaado", "クレジットカード", "クレジットカード", "", "credit card", "", "", 6, 1, deck::Kind::Word},
    {"kata-pointo", "ポイント", "ポイント", "", "points (loyalty scheme); point", "", "", 0, 1, deck::Kind::Word},
    {"kata-pointokaado", "ポイントカード", "ポイントカード", "", "loyalty card", "", "", -1, 1, deck::Kind::Word},
    {"kata-kyasshuresu", "キャッシュレス", "キャッシュレス", "", "cashless", "", "", 1, 1, deck::Kind::Word},
    {"kata-saizu", "サイズ", "サイズ", "", "size", "", "", 1, 1, deck::Kind::Word},
    {"kata-furiisaizu", "フリーサイズ", "フリーサイズ", "", "one size fits all", "not free of charge", "", 4, 1, deck::Kind::Word},
    {"kata-seeru", "セール", "セール", "", "sale", "", "", 1, 1, deck::Kind::Word},
    {"kata-sain", "サイン", "サイン", "", "signature; autograph", "not a signboard: your signature", "", 1, 1, deck::Kind::Word},
    {"kata-pettobotoru", "ペットボトル", "ペットボトル", "", "plastic bottle", "not for pets: PET is the plastic", "", -1, 1, deck::Kind::Word},
    {"kata-biniiru", "ビニール", "ビニール", "", "plastic; vinyl", "not only vinyl: also means plastic", "", 2, 1, deck::Kind::Word},
    {"kata-masuku", "マスク", "マスク", "", "face mask", "マ, not ア or ム", "", 1, 1, deck::Kind::Word},
    {"kata-thisshu", "ティッシュ", "ティッシュ", "", "tissue", "ティ is typed thi", "", 1, 1, deck::Kind::Word},
    {"kata-tabako", "タバコ", "タバコ", "", "cigarettes; tobacco", "from Portuguese 'tabaco'", "", 0, 1, deck::Kind::Word},
    {"kata-wanpiisu", "ワンピース", "ワンピース", "", "dress", "not 'one piece' of something", "", 3, 1, deck::Kind::Word},
    {"kata-shatsu", "シャツ", "シャツ", "", "shirt", "シ first, then ツ", "", 1, 1, deck::Kind::Word},
    {"kata-hoteru", "ホテル", "ホテル", "", "hotel", "テ, not チ", "", 1, 1, deck::Kind::Word},
    {"kata-bijinesuhoteru", "ビジネスホテル", "ビジネスホテル", "", "budget business hotel", "cheap, basic and well located", "", 5, 1, deck::Kind::Word},
    {"kata-penshon", "ペンション", "ペンション", "", "Western-style guest house", "not a pension you are paid", "", 1, 1, deck::Kind::Word},
    {"kata-furonto", "フロント", "フロント", "", "front desk; reception", "not the front of the building", "", 0, 1, deck::Kind::Word},
    {"kata-chekkuin", "チェックイン", "チェックイン", "", "check-in", "チェ is typed che", "", 4, 1, deck::Kind::Word},
    {"kata-chekkuauto", "チェックアウト", "チェックアウト", "", "check-out", "チェ is typed che", "", 4, 1, deck::Kind::Word},
    {"kata-kaadokii", "カードキー", "カードキー", "", "key card", "", "", -1, 1, deck::Kind::Word},
    {"kata-kyanseru", "キャンセル", "キャンセル", "", "cancellation", "", "", 1, 1, deck::Kind::Word},
    {"kata-shinguru", "シングル", "シングル", "", "single; single room", "シ, not ツ", "", 1, 1, deck::Kind::Word},
    {"kata-tsuin", "ツイン", "ツイン", "", "twin; twin room", "ツ, not シ", "", 2, 1, deck::Kind::Word},
    {"kata-daburu", "ダブル", "ダブル", "", "double; double room", "one bed for two; ツイン is two beds", "", 1, 1, deck::Kind::Word},
    {"kata-beddo", "ベッド", "ベッド", "", "bed", "small ッ: typed beddo", "", 1, 1, deck::Kind::Word},
    {"kata-yuusuhosuteru", "ユースホステル", "ユースホステル", "", "youth hostel", "ユ, not コ or ヨ", "", 4, 1, deck::Kind::Word},
    {"kata-shiitsu", "シーツ", "シーツ", "", "bed sheet", "シ first, then ツ", "", 1, 1, deck::Kind::Word},
    {"kata-taoru", "タオル", "タオル", "", "towel", "タ, not ク or ケ", "", 1, 1, deck::Kind::Word},
    {"kata-surippa", "スリッパ", "スリッパ", "", "slippers", "small ッ: typed surippa", "", 1, 1, deck::Kind::Word},
    {"kata-shawaa", "シャワー", "シャワー", "", "shower", "ワ, not ウ or フ", "", 1, 1, deck::Kind::Word},
    {"kata-shanpuu", "シャンプー", "シャンプー", "", "shampoo", "", "", 1, 1, deck::Kind::Word},
    {"kata-rinsu", "リンス", "リンス", "", "hair conditioner; rinse", "on a bottle: hair conditioner", "", 1, 1, deck::Kind::Word},
    {"kata-kondhishonaa", "コンディショナー", "コンディショナー", "", "conditioner", "ディ is typed dhi", "", 3, 1, deck::Kind::Word},
    {"kata-bodhisoopu", "ボディソープ", "ボディソープ", "", "body soap", "ディ is typed dhi; ソ, not ン", "", -1, 1, deck::Kind::Word},
    {"kata-doraiyaa", "ドライヤー", "ドライヤー", "", "hair dryer", "", "", 0, 1, deck::Kind::Word},
    {"kata-yunittobasu", "ユニットバス", "ユニットバス", "", "prefabricated bathroom unit", "not a bus: バス here is a bath", "", 5, 1, deck::Kind::Word},
    {"kata-toire", "トイレ", "トイレ", "", "toilet", "short for トイレット", "", 1, 1, deck::Kind::Word},
    {"kata-toirettopeepaa", "トイレットペーパー", "トイレットペーパー", "", "toilet paper", "", "", 6, 1, deck::Kind::Word},
    {"kata-eakon", "エアコン", "エアコン", "", "air conditioner", "short for エアコンディショナー", "", 0, 1, deck::Kind::Word},
    {"kata-rimokon", "リモコン", "リモコン", "", "remote control", "short for リモートコントロール", "", 0, 1, deck::Kind::Word},
    {"kata-terebi", "テレビ", "テレビ", "", "television", "short for テレビジョン", "", 1, 1, deck::Kind::Word},
    {"kata-konsento", "コンセント", "コンセント", "", "power socket", "not 'consent'", "", 1, 1, deck::Kind::Word},
    {"kata-suitchi", "スイッチ", "スイッチ", "", "switch", "", "", 2, 1, deck::Kind::Word},
    {"kata-sutoobu", "ストーブ", "ストーブ", "", "room heater", "not a cooker: it heats the room", "", 2, 1, deck::Kind::Word},
    {"kata-mooningukooru", "モーニングコール", "モーニングコール", "", "wake-up call", "made in Japan from 'morning call'", "", 6, 1, deck::Kind::Word},
    {"kata-koinrandorii", "コインランドリー", "コインランドリー", "", "launderette", "", "", 4, 1, deck::Kind::Word},
    {"kata-erebeetaa", "エレベーター", "エレベーター", "", "lift", "", "", 3, 1, deck::Kind::Word},
    {"kata-esukareetaa", "エスカレーター", "エスカレーター", "", "escalator", "", "", 4, 1, deck::Kind::Word},
    {"kata-hoomu", "ホーム", "ホーム", "", "platform (at a station)", "not 'home' here: from 'platform'", "", 1, 1, deck::Kind::Word},
    {"kata-hoomudoa", "ホームドア", "ホームドア", "", "platform edge doors", "from '(plat)form door'", "", -1, 1, deck::Kind::Word},
    {"kata-wanman", "ワンマン", "ワンマン", "", "driver-only train or bus", "not a one-man show: no conductor", "", 1, 1, deck::Kind::Word},
    {"kata-daiya", "ダイヤ", "ダイヤ", "", "train timetable", "not a diamond here: from 'diagram'", "", 1, 1, deck::Kind::Word},
    {"kata-chaaji", "チャージ", "チャージ", "", "top-up; charge", "adding money to a smart card", "", 1, 1, deck::Kind::Word},
    {"kata-chiketto", "チケット", "チケット", "", "ticket", "チ and ケ: not テ, not ク", "", 2, 1, deck::Kind::Word},
    {"kata-koinrokkaa", "コインロッカー", "コインロッカー", "", "coin-operated locker", "made in Japan from 'coin locker'", "", 4, 1, deck::Kind::Word},
    {"kata-takushii", "タクシー", "タクシー", "", "taxi", "タ, ク and シ in one word", "", 1, 1, deck::Kind::Word},
    {"kata-basu", "バス", "バス", "", "bus", "ス, not ヌ", "", 1, 1, deck::Kind::Word},
    {"kata-taaminaru", "ターミナル", "ターミナル", "", "terminal", "for buses, or at an airport", "", 1, 1, deck::Kind::Word},
    {"kata-rimujinbasu", "リムジンバス", "リムジンバス", "", "airport bus", "not a limousine: a shuttle bus", "", -1, 1, deck::Kind::Word},
    {"kata-rentakaa", "レンタカー", "レンタカー", "", "hire car", "", "", 3, 1, deck::Kind::Word},
    {"kata-rentasaikuru", "レンタサイクル", "レンタサイクル", "", "bicycle hire", "made in Japan from 'rent-a-cycle'", "", 4, 1, deck::Kind::Word},
    {"kata-gasorinsutando", "ガソリンスタンド", "ガソリンスタンド", "", "petrol station", "made in Japan from 'gasoline stand'", "", 6, 1, deck::Kind::Word},
    {"kata-baiku", "バイク", "バイク", "", "motorbike", "usually a motorbike, not a bicycle", "", 1, 1, deck::Kind::Word},
    {"kata-bebiikaa", "ベビーカー", "ベビーカー", "", "pushchair", "not a small car: from 'baby car'", "", 4, 1, deck::Kind::Word},
    {"kata-manaamoodo", "マナーモード", "マナーモード", "", "silent mode (on a phone)", "made in Japan from 'manner mode'", "", -1, 1, deck::Kind::Word},
    {"kata-suutsukeesu", "スーツケース", "スーツケース", "", "suitcase", "ス, ツ and ケ in one word", "", 4, 1, deck::Kind::Word},
    {"kata-pasupooto", "パスポート", "パスポート", "", "passport", "", "", 3, 1, deck::Kind::Word},
    {"kata-tsuaa", "ツアー", "ツアー", "", "tour", "ツ, not シ; ア, not マ", "", 1, 1, deck::Kind::Word},
    {"kata-mappu", "マップ", "マップ", "", "map", "マ, not ア or ム", "", 1, 1, deck::Kind::Word},
    {"kata-infomeeshon", "インフォメーション", "インフォメーション", "", "information", "フォ is typed fo", "", 4, 1, deck::Kind::Word},
    {"kata-roopuwei", "ロープウェイ", "ロープウェイ", "", "ropeway; aerial cable car", "ウェ is typed we", "", -1, 1, deck::Kind::Word},
    {"kata-monoreeru", "モノレール", "モノレール", "", "monorail", "ノ, not ソ or ン", "", 3, 1, deck::Kind::Word},
    {"kata-sumaho", "スマホ", "スマホ", "", "smartphone", "short for スマートフォン", "", -1, 1, deck::Kind::Word},
    {"kata-pasokon", "パソコン", "パソコン", "", "personal computer", "short for パーソナルコンピューター", "", 0, 1, deck::Kind::Word},
    {"kata-apuri", "アプリ", "アプリ", "", "app", "short for アプリケーションソフト", "", -1, 1, deck::Kind::Word},
    {"kata-manshon", "マンション", "マンション", "", "flat; block of flats", "not a mansion", "", 1, 1, deck::Kind::Word},
    {"kata-karaoke", "カラオケ", "カラオケ", "", "karaoke", "from 'empty' and 'orchestra'", "", -1, 1, deck::Kind::Word},
    {"kata-famiresu", "ファミレス", "ファミレス", "", "family restaurant", "short for ファミリーレストラン", "", -1, 1, deck::Kind::Word},
};

const deck::Item kItems_signs[] = {
    {"sign-eki", "駅", "えき", "", "station", "", "駅 station", 1, 2, deck::Kind::Word},
    {"sign-iriguchi", "入口", "いりぐち", "", "entrance", "", "入 enter  口 opening", 0, 2, deck::Kind::Word},
    {"sign-deguchi", "出口", "でぐち", "", "exit", "", "出 go out  口 opening", 1, 2, deck::Kind::Word},
    {"sign-kaisatsuguchi", "改札口", "かいさつぐち", "", "ticket gate", "", "改 inspect  札 ticket  口 opening", 4, 2, deck::Kind::Word},
    {"sign-kitaguchi", "北口", "きたぐち", "", "north exit", "", "北 north  口 opening", -1, 2, deck::Kind::Word},
    {"sign-minamiguchi", "南口", "みなみぐち", "", "south exit", "", "南 south  口 opening", -1, 2, deck::Kind::Word},
    {"sign-higashiguchi", "東口", "ひがしぐち", "", "east exit", "", "東 east  口 opening", -1, 2, deck::Kind::Word},
    {"sign-nishiguchi", "西口", "にしぐち", "", "west exit", "", "西 west  口 opening", -1, 2, deck::Kind::Word},
    {"sign-chikatetsu", "地下鉄", "ちかてつ", "", "underground; subway", "", "地 ground  下 below  鉄 railway", 0, 2, deck::Kind::Word},
    {"sign-noriba", "のりば", "のりば", "", "boarding place", "platform, bus stop or taxi rank", "", -1, 1, deck::Kind::Word},
    {"sign-norikae", "のりかえ", "のりかえ", "", "transfer", "follow it to change lines", "", -1, 1, deck::Kind::Word},
    {"sign-kippuuriba", "きっぷうりば", "きっぷうりば", "", "ticket office", "", "", -1, 1, deck::Kind::Word},
    {"sign-kenbaiki", "券売機", "けんばいき", "", "ticket machine", "", "券 ticket  売 sell  機 machine", 3, 2, deck::Kind::Word},
    {"sign-seisanki", "精算機", "せいさんき", "", "fare adjustment machine", "pay what is missing before the gate", "精 exact  算 calculate  機 machine", -1, 2, deck::Kind::Word},
    {"sign-houmen", "方面", "ほうめん", "", "direction", "after a place name: towards it", "方 direction  面 face", 3, 2, deck::Kind::Word},
    {"sign-yuki", "行き", "ゆき", "いき", "bound for", "after a place name: the last stop", "行 go", 0, 2, deck::Kind::Word},
    {"sign-bansen", "番線", "ばんせん", "", "platform number", "3番線 is platform 3", "番 number  線 line", 0, 2, deck::Kind::Word},
    {"sign-kakuekiteisha", "各駅停車", "かくえきていしゃ", "", "train stopping at every station", "", "各 each  駅 station  停 stop  車 car", 5, 2, deck::Kind::Word},
    {"sign-futsuu", "普通", "ふつう", "", "ordinary; local train", "stops at every station", "普 general  通 pass through", 0, 3, deck::Kind::Word},
    {"sign-kaisoku", "快速", "かいそく", "", "rapid train", "skips some stations", "快 rapid  速 fast", 0, 2, deck::Kind::Word},
    {"sign-kyuukou", "急行", "きゅうこう", "", "express train", "skips stations; check where it stops", "急 hurry  行 go", 0, 2, deck::Kind::Word},
    {"sign-tokkyuu", "特急", "とっきゅう", "", "limited express", "often needs an extra ticket", "特 special  急 hurry", 0, 2, deck::Kind::Word},
    {"sign-shinkansen", "新幹線", "しんかんせん", "", "Shinkansen; bullet train", "", "新 new  幹 trunk  線 line", 3, 2, deck::Kind::Word},
    {"sign-gousha", "号車", "ごうしゃ", "", "car number", "5号車 is car 5", "号 number  車 car", -1, 2, deck::Kind::Word},
    {"sign-jiyuuseki", "自由席", "じゆうせき", "", "unreserved seat", "sit on any free seat", "自 self  由 reason  席 seat", 2, 2, deck::Kind::Word},
    {"sign-shiteiseki", "指定席", "していせき", "", "reserved seat", "the seat number is on the ticket", "指 point  定 fix  席 seat", 2, 2, deck::Kind::Word},
    {"sign-yuusenseki", "優先席", "ゆうせんせき", "", "priority seat", "give it up to those who need it", "優 superior  先 ahead  席 seat", -1, 2, deck::Kind::Word},
    {"sign-joseisen-yousha", "女性専用車", "じょせいせんようしゃ", "", "women-only car", "", "女 woman  性 gender  専 exclusive  用 use  車 car", -1, 2, deck::Kind::Word},
    {"sign-shihatsu", "始発", "しはつ", "", "first train; starting here", "", "始 begin  発 depart", 0, 2, deck::Kind::Word},
    {"sign-saishuu", "最終", "さいしゅう", "", "last; last train or bus", "", "最 most  終 end", 0, 2, deck::Kind::Word},
    {"sign-kaisou", "回送", "かいそう", "", "not in service", "do not board", "回 round  送 send", 0, 2, deck::Kind::Word},
    {"sign-chien", "遅延", "ちえん", "", "delay", "", "遅 late  延 prolong", 0, 3, deck::Kind::Word},
    {"sign-unkyuu", "運休", "うんきゅう", "", "service cancelled", "", "運 transport  休 rest", 0, 2, deck::Kind::Word},
    {"sign-untenmiawase", "運転見合わせ", "うんてんみあわせ", "", "service suspended", "no trains for the time being", "運 transport  転 turn  見 see  合 join", -1, 2, deck::Kind::Word},
    {"sign-katamichi", "片道", "かたみち", "", "one way", "", "片 one-sided  道 road", 0, 2, deck::Kind::Word},
    {"sign-oufuku", "往復", "おうふく", "", "return; round trip", "", "往 go  復 return", 0, 2, deck::Kind::Word},
    {"sign-unchin", "運賃", "うんちん", "", "fare", "the price of the ride", "運 transport  賃 charge", 1, 2, deck::Kind::Word},
    {"sign-otona", "大人", "おとな", "だいにん", "adult", "", "大 large  人 person", 0, 2, deck::Kind::Word},
    {"sign-shounin", "小人", "しょうにん", "こども", "child", "the child price on a fare table", "小 small  人 person", 0, 2, deck::Kind::Word},
    {"sign-joushaken", "乗車券", "じょうしゃけん", "", "fare ticket", "the basic ticket for the ride", "乗 ride  車 car  券 ticket", 3, 2, deck::Kind::Word},
    {"sign-tokkyuuken", "特急券", "とっきゅうけん", "", "limited express ticket", "needed on top of the 乗車券", "特 special  急 hurry  券 ticket", -1, 2, deck::Kind::Word},
    {"sign-seiriken", "整理券", "せいりけん", "", "numbered ticket", "bus: take one when you board", "整 organise  理 arrange  券 ticket", -1, 2, deck::Kind::Word},
    {"sign-ryougae", "両替", "りょうがえ", "", "money changing", "bus: changes a note into coins", "両 old coin  替 exchange", 0, 3, deck::Kind::Word},
    {"sign-eigyouchuu", "営業中", "えいぎょうちゅう", "", "open for business", "", "営 conduct  業 business  中 in", -1, 2, deck::Kind::Word},
    {"sign-junbichuu", "準備中", "じゅんびちゅう", "", "in preparation", "getting ready: not open yet", "準 prepare  備 equip  中 in", -1, 2, deck::Kind::Word},
    {"sign-eigyoujikan", "営業時間", "えいぎょうじかん", "", "opening hours", "", "営 conduct  業 business  時 time  間 interval", -1, 2, deck::Kind::Word},
    {"sign-teikyuubi", "定休日", "ていきゅうび", "", "regular closing day", "", "定 fix  休 rest  日 day", 3, 2, deck::Kind::Word},
    {"sign-honjitsukyuugyou", "本日休業", "ほんじつきゅうぎょう", "", "closed today", "", "本 present  日 day  休 rest  業 business", -1, 2, deck::Kind::Word},
    {"sign-jidou", "自動", "じどう", "", "automatic", "自動ドア: the door opens by itself", "自 self  動 move", 0, 2, deck::Kind::Word},
    {"sign-osu", "押す", "おす", "", "to push", "doors often show only 押", "押 push", 0, 3, deck::Kind::Word},
    {"sign-hiku", "引く", "ひく", "", "to pull", "doors often show only 引", "引 pull", 0, 2, deck::Kind::Word},
    {"sign-uketsuke", "受付", "うけつけ", "", "reception", "report here first", "受 receive  付 attach", 0, 2, deck::Kind::Word},
    {"sign-manseki", "満席", "まんせき", "", "all seats taken", "", "満 full  席 seat", 0, 2, deck::Kind::Word},
    {"sign-manshitsu", "満室", "まんしつ", "", "no vacancy", "every room is taken", "満 full  室 room", 0, 2, deck::Kind::Word},
    {"sign-yoyakusei", "予約制", "よやくせい", "", "reservation system", "you need to book ahead", "予 beforehand  約 promise  制 system", -1, 2, deck::Kind::Word},
    {"sign-kashikiri", "貸切", "かしきり", "", "booked for private use", "closed to other guests", "貸 lend  切 cut", 0, 2, deck::Kind::Word},
    {"sign-okaikei", "お会計", "おかいけい", "", "bill; payment", "pay here", "会 reckon  計 measure", -1, 2, deck::Kind::Word},
    {"sign-ryoukin", "料金", "りょうきん", "", "charge; fee", "", "料 fee  金 money", 1, 2, deck::Kind::Word},
    {"sign-genkinnomi", "現金のみ", "げんきんのみ", "", "cash only", "cards are not accepted", "現 actual  金 money", -1, 2, deck::Kind::Word},
    {"sign-fuka", "不可", "ふか", "", "not allowed", "カード不可: cards not accepted", "不 not  可 can", 2, 2, deck::Kind::Word},
    {"sign-menzei", "免税", "めんぜい", "", "tax exemption", "tax-free sales: passport needed", "免 exempt  税 tax", 0, 3, deck::Kind::Word},
    {"sign-zeikomi", "税込", "ぜいこみ", "", "tax included", "", "税 tax  込 included", 0, 3, deck::Kind::Word},
    {"sign-zeinuki", "税抜", "ぜいぬき", "", "tax excluded", "tax is added when you pay", "税 tax  抜 remove", -1, 3, deck::Kind::Word},
    {"sign-waribiki", "割引", "わりびき", "", "discount", "2割引 is 20% off", "割 divide  引 pull", 0, 2, deck::Kind::Word},
    {"sign-hangaku", "半額", "はんがく", "", "half price", "", "半 half  額 amount", 0, 2, deck::Kind::Word},
    {"sign-muryou", "無料", "むりょう", "", "free of charge", "", "無 none  料 fee", 0, 2, deck::Kind::Word},
    {"sign-yuuryou", "有料", "ゆうりょう", "", "charged; not free", "the opposite of 無料", "有 have  料 fee", 0, 2, deck::Kind::Word},
    {"sign-kin-en", "禁煙", "きんえん", "", "no smoking", "", "禁 forbid  煙 smoke", 0, 3, deck::Kind::Word},
    {"sign-kitsuenjo", "喫煙所", "きつえんじょ", "きつえんしょ", "smoking area", "", "喫 consume  煙 smoke  所 place", -1, 3, deck::Kind::Word},
    {"sign-dosokugenkin", "土足厳禁", "どそくげんきん", "", "shoes strictly prohibited", "take your shoes off", "土 soil  足 foot  厳 strict  禁 forbid", -1, 2, deck::Kind::Word},
    {"sign-heiten", "閉店", "へいてん", "", "shop closing; closed", "", "閉 shut  店 shop", 0, 2, deck::Kind::Word},
    {"sign-shinagire", "品切れ", "しなぎれ", "", "out of stock", "", "品 goods  切 cut", 0, 2, deck::Kind::Word},
    {"sign-mochikaeri", "持ち帰り", "もちかえり", "", "takeaway", "", "持 hold  帰 return home", 0, 2, deck::Kind::Word},
    {"sign-tennai", "店内", "てんない", "", "inside the shop", "order screens: 店内 is eating in", "店 shop  内 inside", 1, 2, deck::Kind::Word},
    {"sign-satsueikinshi", "撮影禁止", "さつえいきんし", "", "no photography", "", "撮 photograph  影 shadow  禁 forbid  止 stop", -1, 3, deck::Kind::Word},
    {"sign-tachiirikinshi", "立入禁止", "たちいりきんし", "", "no entry", "関係者以外立入禁止: staff only", "立 stand  入 enter  禁 forbid  止 stop", 0, 2, deck::Kind::Word},
    {"sign-koshouchuu", "故障中", "こしょうちゅう", "", "out of order", "", "故 accident  障 hinder  中 in", -1, 2, deck::Kind::Word},
    {"sign-shiyouchuu", "使用中", "しようちゅう", "", "in use; occupied", "", "使 use  用 use  中 in", -1, 2, deck::Kind::Word},
    {"sign-seisouchuu", "清掃中", "せいそうちゅう", "", "being cleaned", "", "清 clean  掃 sweep  中 in", -1, 3, deck::Kind::Word},
    {"sign-saikoubi", "最後尾", "さいこうび", "", "end of the queue", "join the queue here", "最 most  後 behind  尾 tail", 3, 3, deck::Kind::Word},
    {"sign-okotowari", "お断り", "おことわり", "", "refusal", "what it names is not accepted", "断 refuse", -1, 2, deck::Kind::Word},
    {"sign-shokken", "食券", "しょっけん", "", "meal ticket", "buy at the machine, hand to staff", "食 food  券 ticket", 0, 2, deck::Kind::Word},
    {"sign-chuumon", "注文", "ちゅうもん", "", "order", "注文はこちら: order here", "注 note  文 writing", 0, 2, deck::Kind::Word},
    {"sign-urikire", "売切", "うりきれ", "", "sold out", "", "売 sell  切 cut", 0, 2, deck::Kind::Word},
    {"sign-teishoku", "定食", "ていしょく", "", "set meal", "", "定 fix  食 food", 0, 2, deck::Kind::Word},
    {"sign-higawari", "日替わり", "ひがわり", "", "changing every day", "the dish of the day", "日 day  替 exchange", 0, 3, deck::Kind::Word},
    {"sign-tanpin", "単品", "たんぴん", "", "single item", "the dish alone, not a set", "単 single  品 goods", 0, 2, deck::Kind::Word},
    {"sign-oomori", "大盛", "おおもり", "", "large portion", "", "大 large  盛 serving", 0, 2, deck::Kind::Word},
    {"sign-namimori", "並盛", "なみもり", "", "regular portion", "", "並 normal  盛 serving", -1, 2, deck::Kind::Word},
    {"sign-kaedama", "替玉", "かえだま", "", "second serving of noodles", "ramen: more noodles for your soup", "替 exchange  玉 ball", 0, 3, deck::Kind::Word},
    {"sign-okawari", "おかわり", "おかわり", "", "second helping; refill", "", "", -1, 1, deck::Kind::Word},
    {"sign-tabehoudai", "食べ放題", "たべほうだい", "", "all you can eat", "", "食 food  放 set free  題 topic", -1, 2, deck::Kind::Word},
    {"sign-nomihoudai", "飲み放題", "のみほうだい", "", "all you can drink", "", "飲 drink  放 set free  題 topic", -1, 2, deck::Kind::Word},
    {"sign-otooshi", "お通し", "おとおし", "", "appetiser", "izakaya: served and charged unasked", "通 pass through", 0, 2, deck::Kind::Word},
    {"sign-osusume", "おすすめ", "おすすめ", "", "recommendation", "", "", -1, 1, deck::Kind::Word},
    {"sign-atatakai", "あたたかい", "あたたかい", "", "warm; hot", "vending machine: hot drink", "", -1, 1, deck::Kind::Word},
    {"sign-tsumetai", "つめたい", "つめたい", "", "cold", "vending machine: cold drink", "", -1, 1, deck::Kind::Word},
    {"sign-serufusaabisu", "セルフサービス", "セルフサービス", "", "self-service", "fetch it yourself, for example water", "", 4, 1, deck::Kind::Word},
    {"sign-otsuri", "おつり", "おつり", "", "change (money back)", "", "", -1, 1, deck::Kind::Word},
    {"sign-torikeshi", "取消", "とりけし", "", "cancel", "", "取 take  消 cancel", 0, 2, deck::Kind::Word},
    {"sign-kakunin", "確認", "かくにん", "", "confirm; check", "button: confirm what you entered", "確 firm  認 recognise", 0, 2, deck::Kind::Word},
    {"sign-modoru", "戻る", "もどる", "", "to go back", "screen button: back one step", "戻 go back", 2, 3, deck::Kind::Word},
    {"sign-yobidashi", "呼出", "よびだし", "", "call", "calls staff; in a toilet, calls help", "呼 call  出 go out", 0, 2, deck::Kind::Word},
    {"sign-ryoushuusho", "領収書", "りょうしゅうしょ", "", "receipt", "", "領 receive  収 obtain  書 write", 0, 2, deck::Kind::Word},
    {"sign-henkyakuguchi", "返却口", "へんきゃくぐち", "", "return slot; tray return", "", "返 return  却 withdraw  口 opening", -1, 3, deck::Kind::Word},
    {"sign-reibou", "冷房", "れいぼう", "", "air conditioning; cooling", "", "冷 cool  房 room", 0, 3, deck::Kind::Word},
    {"sign-danbou", "暖房", "だんぼう", "", "heating", "", "暖 warm  房 room", 0, 3, deck::Kind::Word},
    {"sign-joshitsu", "除湿", "じょしつ", "", "dehumidification", "", "除 remove  湿 damp", 0, 3, deck::Kind::Word},
    {"sign-unten", "運転", "うんてん", "", "operation; running", "air conditioner: 運転/停止 is on/off", "運 transport  転 turn", 0, 2, deck::Kind::Word},
    {"sign-teishi", "停止", "ていし", "", "stop", "toilet panels often show only 止", "停 stop  止 stop", 0, 2, deck::Kind::Word},
    {"sign-ondo", "温度", "おんど", "", "temperature", "", "温 warm  度 degree", 1, 2, deck::Kind::Word},
    {"sign-dengen", "電源", "でんげん", "", "power", "switches: 入 is on, 切 is off", "電 electricity  源 source", 0, 2, deck::Kind::Word},
    {"sign-nagasu", "流す", "ながす", "", "to flush", "", "流 flow", 2, 2, deck::Kind::Word},
    {"sign-dai", "大", "だい", "", "large", "toilet: full flush; menu: large", "大 large", 1, 2, deck::Kind::Word},
    {"sign-shou", "小", "しょう", "", "small", "toilet: light flush; menu: small", "小 small", 1, 2, deck::Kind::Word},
    {"sign-oshiri", "おしり", "おしり", "", "bottom", "toilet: rear wash", "", -1, 1, deck::Kind::Word},
    {"sign-bide", "ビデ", "ビデ", "", "bidet", "toilet: front wash", "", 1, 1, deck::Kind::Word},
    {"sign-otearai", "お手洗い", "おてあらい", "", "toilet", "", "手 hand  洗 wash", 3, 2, deck::Kind::Word},
    {"sign-keshoushitsu", "化粧室", "けしょうしつ", "", "toilet; powder room", "", "化 change  粧 adorn  室 room", 2, 3, deck::Kind::Word},
    {"sign-otoko", "男", "おとこ", "", "man", "on toilet and bath doors", "男 man", 3, 2, deck::Kind::Word},
    {"sign-onna", "女", "おんな", "", "woman", "on toilet and bath doors", "女 woman", 3, 2, deck::Kind::Word},
    {"sign-otokoyu", "男湯", "おとこゆ", "", "men's bath", "", "男 man  湯 hot water", 0, 2, deck::Kind::Word},
    {"sign-onnayu", "女湯", "おんなゆ", "", "women's bath", "", "女 woman  湯 hot water", 0, 2, deck::Kind::Word},
    {"sign-hijouguchi", "非常口", "ひじょうぐち", "", "emergency exit", "", "非 not  常 usual  口 opening", 2, 2, deck::Kind::Word},
    {"sign-daiyokujou", "大浴場", "だいよくじょう", "", "large shared bath", "", "大 large  浴 bathe  場 place", -1, 2, deck::Kind::Word},
    {"sign-rotenburo", "露天風呂", "ろてんぶろ", "", "open-air bath", "", "露 expose  天 sky  風 wind  呂 spine", 0, 3, deck::Kind::Word},
    {"sign-datsuijo", "脱衣所", "だついじょ", "だついしょ", "changing room", "", "脱 take off  衣 clothes  所 place", 0, 3, deck::Kind::Word},
    {"sign-kakeyu", "かけ湯", "かけゆ", "", "rinse before the bath", "pour hot water over yourself first", "湯 hot water", -1, 2, deck::Kind::Word},
    {"sign-irezumi", "入れ墨", "いれずみ", "", "tattoo", "many baths refuse tattoos", "入 enter  墨 ink", 0, 3, deck::Kind::Word},
    {"sign-hiraku", "開く", "ひらく", "あく", "to open", "lift button: 開", "開 open", 2, 2, deck::Kind::Word},
    {"sign-shimeru", "閉める", "しめる", "", "to close", "lift button: 閉", "閉 shut", 2, 2, deck::Kind::Word},
    {"sign-tomare", "止まれ", "とまれ", "", "stop", "", "止 stop", -1, 2, deck::Kind::Word},
    {"sign-koujichuu", "工事中", "こうじちゅう", "", "under construction", "", "工 construction  事 matter  中 in", -1, 2, deck::Kind::Word},
    {"sign-tsuukoudome", "通行止", "つうこうどめ", "", "road closed", "", "通 pass through  行 go  止 stop", 0, 2, deck::Kind::Word},
    {"sign-kiken", "危険", "きけん", "", "danger", "", "危 dangerous  険 steep", 0, 2, deck::Kind::Word},
    {"sign-chuui", "注意", "ちゅうい", "", "caution", "", "注 note  意 mind", 1, 2, deck::Kind::Word},
    {"sign-ashimoto", "足元", "あしもと", "", "underfoot; one's step", "足元注意: mind your step", "足 foot  元 origin", 3, 2, deck::Kind::Word},
    {"sign-chuurinjou", "駐輪場", "ちゅうりんじょう", "", "bicycle parking", "", "駐 stay  輪 wheel  場 place", 0, 3, deck::Kind::Word},
    {"sign-kuusha", "空車", "くうしゃ", "", "vacant", "taxi for hire; car park has room", "空 empty  車 car", 0, 2, deck::Kind::Word},
    {"sign-kouban", "交番", "こうばん", "", "police box", "", "交 alternate  番 number", 0, 2, deck::Kind::Word},
    {"sign-yakkyoku", "薬局", "やっきょく", "", "pharmacy", "", "薬 medicine  局 office", 0, 2, deck::Kind::Word},
    {"sign-yuubinkyoku", "郵便局", "ゆうびんきょく", "", "post office", "", "郵 mail  便 letter  局 office", 3, 2, deck::Kind::Word},
    {"sign-annaijo", "案内所", "あんないじょ", "", "information desk", "", "案 plan  内 inside  所 place", 0, 2, deck::Kind::Word},
    {"sign-hinanjo", "避難所", "ひなんじょ", "", "evacuation shelter", "", "避 avoid  難 trouble  所 place", 0, 3, deck::Kind::Word},
    {"sign-tsunami", "津波", "つなみ", "", "tsunami", "", "津 harbour  波 wave", 0, 3, deck::Kind::Word},
    {"sign-haikanryou", "拝観料", "はいかんりょう", "", "admission fee", "the word used at temples", "拝 worship  観 view  料 fee", 3, 2, deck::Kind::Word},
    {"sign-junro", "順路", "じゅんろ", "", "suggested route", "follow it through the building", "順 order  路 route", 1, 2, deck::Kind::Word},
    {"sign-kyuukanbi", "休館日", "きゅうかんび", "", "closed day", "of a museum, library or hall", "休 rest  館 building  日 day", 3, 2, deck::Kind::Word},
    {"sign-heijitsu", "平日", "へいじつ", "", "weekday", "", "平 ordinary  日 day", 0, 2, deck::Kind::Word},
    {"sign-shukujitsu", "祝日", "しゅくじつ", "", "public holiday", "土日祝: Sat, Sun and holidays", "祝 celebrate  日 day", 0, 2, deck::Kind::Word},
    {"sign-moerugomi", "燃えるゴミ", "もえるごみ", "", "burnable rubbish", "", "燃 burn", -1, 2, deck::Kind::Word},
    {"sign-sen-you", "専用", "せんよう", "", "exclusive use", "after a word: only for that", "専 exclusive  用 use", 0, 2, deck::Kind::Word},
    {"sign-kinshi", "禁止", "きんし", "", "prohibited", "", "禁 forbid  止 stop", 0, 2, deck::Kind::Word},
    {"sign-inshokukinshi", "飲食禁止", "いんしょくきんし", "", "no food or drink", "", "飲 drink  食 food  禁 forbid  止 stop", -1, 2, deck::Kind::Word},
};

}  // namespace

extern const deck::Deck kDeckTable[] = {
    {"hiragana", "ひらがな", "hiragana", kItems_hiragana, 104, 1},
    {"katakana", "カタカナ", "katakana", kItems_katakana, 104, 2},
    {"numbers", "すうじ", "numbers", kItems_numbers, 104, 2},
    {"counters", "かぞえかた", "counters", kItems_counters, 138, 2},
    {"katakana-words", "カタカナご", "katakana words", kItems_katakana_words, 164, 3},
    {"signs", "かんばん", "signs", kItems_signs, 154, 3},
};
extern const size_t kDeckTableSize = sizeof(kDeckTable) / sizeof(kDeckTable[0]);

extern const deck::BuddyLine kBuddyLines[] = {
    {"buddy-greeting-01", "greeting", "こんにちは！", "Hello!"},
    {"buddy-greeting-02", "greeting", "また あえたね。", "Nice to see you again."},
    {"buddy-greeting-03", "greeting", "げんき？", "How are you?"},
    {"buddy-greeting-04", "greeting", "まってたよ。", "I was waiting for you."},
    {"buddy-greeting-05", "greeting", "きょうも よろしくね。", "Be kind to me again today."},
    {"buddy-greeting-06", "greeting", "いっしょに やろう。", "Let's do it together."},
    {"buddy-greeting-07", "greeting", "きょうは なに する？", "What shall we do today?"},
    {"buddy-greeting-08", "greeting", "すこし やって みる？", "Want to try a little?"},
    {"buddy-greeting-09", "greeting", "きて くれて うれしい。", "I'm glad you came."},
    {"buddy-start-01", "start", "さあ、 はじめよう。", "Right, let's begin."},
    {"buddy-start-02", "start", "じゅんびは いい？", "Are you ready?"},
    {"buddy-start-03", "start", "ゆっくりで いいよ。", "Take your time."},
    {"buddy-start-04", "start", "じぶんの ペースで。", "At your own pace."},
    {"buddy-start-05", "start", "きらくに いこう。", "Let's keep it relaxed."},
    {"buddy-start-06", "start", "よし、 いこう！", "Right, let's go!"},
    {"buddy-start-07", "start", "れんしゅう しよう。", "Let's practise."},
    {"buddy-start-08", "start", "たのしく やろう。", "Let's enjoy this."},
    {"buddy-start-09", "start", "あせらなくて いいよ。", "No need to hurry."},
    {"buddy-right-01", "right", "せいかい！", "Correct!"},
    {"buddy-right-02", "right", "あたり！", "You got it!"},
    {"buddy-right-03", "right", "その とおり！", "That's right!"},
    {"buddy-right-04", "right", "あってるよ！", "You've got it right!"},
    {"buddy-right-05", "right", "いいね！", "Nice!"},
    {"buddy-right-06", "right", "すごい！", "Great!"},
    {"buddy-right-07", "right", "やったね！", "You did it!"},
    {"buddy-right-08", "right", "さすが！", "Just what I expected of you!"},
    {"buddy-right-09", "right", "ナイス！", "Nice one!"},
    {"buddy-right-10", "right", "かんぺき！", "Perfect!"},
    {"buddy-right-11", "right", "おぼえてるね。", "You remember it."},
    {"buddy-streak-01", "streak", "その ちょうし！", "Keep it up!"},
    {"buddy-streak-02", "streak", "ちょうし いいね！", "You're in good form!"},
    {"buddy-streak-03", "streak", "れんぞく せいかい！", "A run of right answers!"},
    {"buddy-streak-04", "streak", "すごい、 つづいてる！", "Wow, you're on a run!"},
    {"buddy-streak-05", "streak", "とまらないね！", "There's no stopping you!"},
    {"buddy-streak-06", "streak", "どんどん いこう！", "Let's keep going!"},
    {"buddy-streak-07", "streak", "ぜっこうちょう！", "You're on top form!"},
    {"buddy-streak-08", "streak", "いい かんじ！", "Looking good!"},
    {"buddy-streak-09", "streak", "まだまだ いけるね。", "You can go further yet."},
    {"buddy-wrong-01", "wrong", "だいじょうぶだよ。", "It's all right."},
    {"buddy-wrong-02", "wrong", "きに しないで。", "Don't worry about it."},
    {"buddy-wrong-03", "wrong", "つぎは できるよ。", "You'll get it next time."},
    {"buddy-wrong-04", "wrong", "もう いちど みよう。", "Let's look once more."},
    {"buddy-wrong-05", "wrong", "まちがえても いいよ。", "It's fine to get it wrong."},
    {"buddy-wrong-06", "wrong", "これは むずかしいね。", "This one is hard, isn't it?"},
    {"buddy-wrong-07", "wrong", "だれでも まちがえるよ。", "Everyone gets things wrong."},
    {"buddy-wrong-08", "wrong", "また でて くるよ。", "It will come round again."},
    {"buddy-wrong-09", "wrong", "ななころび やおき。", "Fall seven times, rise eight."},
    {"buddy-wrong-10", "wrong", "これから おぼえよう。", "We can learn it from here."},
    {"buddy-almost-01", "almost", "おしい！", "So close!"},
    {"buddy-almost-02", "almost", "もう すこし！", "Nearly there!"},
    {"buddy-almost-03", "almost", "あと ちょっと！", "Just a little more!"},
    {"buddy-almost-04", "almost", "あと いっぽ！", "One more step!"},
    {"buddy-almost-05", "almost", "ほとんど あってるよ。", "It's nearly right."},
    {"buddy-almost-06", "almost", "すこし ちがうよ。", "It's a little off."},
    {"buddy-almost-07", "almost", "ちかい！", "Close!"},
    {"buddy-almost-08", "almost", "もう いっかい！", "Once more!"},
    {"buddy-almost-09", "almost", "よく みて みよう。", "Let's look closely."},
    {"buddy-finish-01", "finish", "おつかれさま！", "Good work!"},
    {"buddy-finish-02", "finish", "よく がんばったね。", "You worked hard."},
    {"buddy-finish-03", "finish", "ぜんぶ おわったよ。", "All done."},
    {"buddy-finish-04", "finish", "また やろうね。", "Let's do this again."},
    {"buddy-finish-05", "finish", "すこし やすもう。", "Let's rest a little."},
    {"buddy-finish-06", "finish", "たのしかったね。", "That was fun."},
    {"buddy-finish-07", "finish", "ありがとう。 またね。", "Thanks. See you."},
    {"buddy-finish-08", "finish", "すこしずつ すすもう。", "Let's go forward bit by bit."},
    {"buddy-finish-09", "finish", "おちゃに しよう。", "Let's stop for some tea."},
    {"buddy-back-01", "back", "おかえり！", "Welcome back!"},
    {"buddy-back-02", "back", "ひさしぶり！", "It's been a while!"},
    {"buddy-back-03", "back", "げんきだった？", "Have you been well?"},
    {"buddy-back-04", "back", "また あえて うれしい。", "Glad to see you again."},
    {"buddy-back-05", "back", "ゆっくり はじめよう。", "Let's start gently."},
    {"buddy-back-06", "back", "わすれても へいきだよ。", "It's fine if you've forgotten."},
    {"buddy-back-07", "back", "すぐ おもいだせるよ。", "It will soon come back to you."},
    {"buddy-back-08", "back", "やすむのも だいじだよ。", "Rest matters too."},
    {"buddy-back-09", "back", "また いっしょだね。", "Together again."},
    {"buddy-low-battery-01", "low-battery", "でんちが すくないよ。", "The battery is low."},
    {"buddy-low-battery-02", "low-battery", "おなかが すいた。", "I'm hungry."},
    {"buddy-low-battery-03", "low-battery", "じゅうでん してね。", "Charge me, please."},
    {"buddy-low-battery-04", "low-battery", "パワーが たりない。", "I'm short of power."},
    {"buddy-low-battery-05", "low-battery", "でんきを ください。", "Some electricity, please."},
    {"buddy-low-battery-06", "low-battery", "そろそろ じゅうでん？", "About time for a charge?"},
    {"buddy-low-battery-07", "low-battery", "ちからが でない。", "I've no strength left."},
    {"buddy-low-battery-08", "low-battery", "ケーブルは ある？", "Have you got a cable?"},
    {"buddy-low-battery-09", "low-battery", "でんちが ピンチ！", "The battery is in a tight spot!"},
    {"buddy-idle-01", "idle", "ひまだなあ。", "Nothing to do..."},
    {"buddy-idle-02", "idle", "まだ いる？", "Still there?"},
    {"buddy-idle-03", "idle", "おーい。", "Hello-o?"},
    {"buddy-idle-04", "idle", "ねむく なって きた。", "I'm getting sleepy."},
    {"buddy-idle-05", "idle", "なにか やる？", "Shall we do something?"},
    {"buddy-idle-06", "idle", "いつでも いいよ。", "Whenever you like."},
    {"buddy-idle-07", "idle", "ここに いるよ。", "I'm right here."},
    {"buddy-idle-08", "idle", "キーを おして みて。", "Try pressing a key."},
    {"buddy-idle-09", "idle", "のんびり しよう。", "Let's take it easy."},
};
extern const size_t kBuddyLineCount = 93;

extern const deck::GuidePage kGuidePages[] = {
    {"", "", "", ""},  // an array cannot be empty; the count below is 0
};
extern const size_t kGuidePageCount = 0;
